### ISSUE TITLE
Create Dataset Loader for ChEBI (NACTEM)

### ISSUE THREAD

**Issue by leonweber** [bigscience-workshop/biomedical#114]
Task: NER, RE
License: Creative Commons 4.0
Format: brat
Language: English
Citation: @InProceedings{Shardlow2018,
  author     = {Shardlow, M J and Nguyen, N and Owen, G and O'Donovan, C and Leach, A and McNaught, J and Turner, S and Ananiadou, S},
  booktitle  = {Proceedings of the Eleventh International Conference on Language Resources and Evaluation ({LREC} 2018)},
  title      = {A New Corpus to Support Text Mining for the Curation of Metabolites in the {ChEBI} Database},
  year       = {2018},
  month      = may,
  pages      = {280--285},
  conference = {Eleventh International Conference on Language Resources and Evaluation (LREC 2018)},
  language   = {en},
  location   = {Miyazaki, Japan},
}

Source: http://www.nactem.ac.uk/chebi/ChEBI.zip

**Comment by mart1nro** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @mart1nro, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by mart1nro** [comment]
@hakunanatasha I'm still working in this.

**Comment by hakunanatasha** [comment]
thank you for letting us know!
