### ISSUE TITLE
Create a dataset loader for CellFinder

### ISSUE THREAD

**Issue by leonweber** [bigscience-workshop/biomedical#115]
Task: NER
License: ???
Format: brat
Language: English
@InProceedings{Neves2012,
  author      = {Neves, Mariana and Damaschun, Alexander and Kurtz, Andreas and Leser, Ulf},
  booktitle   = {Proceedings of the Third Workshop on Building and Evaluation Resources for Biomedical Text Mining ({BioTxtM} 2012) at Language Resources and Evaluation ({LREC)}. Istanbul, Turkey},
  title       = {Annotating and evaluating text for stem cell research},
  year        = {2012},
  pages       = {16--23},
  publisher   = {Citeseer},
}
source: https://www.informatik.hu-berlin.de/de/forschung/gebiete/wbi/resources/cellfinder/cellfinder1_brat.tar.gz

**Comment by sidkiblawi** [comment]
#self-assign

**Comment by sidkiblawi** [comment]
Submitted PR https://github.com/bigscience-workshop/biomedical/pull/359
