### ISSUE TITLE
Create dataset loader for GNormPlus corpus (BC2GM+BC2GN) 

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#117]
- Task: NER, NEN
- License: ? ("freely available from website")
- Format: BioC/PubTattor
- Language: English
- Citation:
Wei C-H, Kao H-Y, Lu Z. GNormPlus: An Integrative Approach for Tagging Gene, Gene Family and Protein Domain. BioMed Research International Journal, Text Mining for Translational Bioinformatics special issue, BioMed Research International Journal, Article ID 918710; DOI: dx.doi.org/10.1155/2015/918710 (2015)

- Source: 
- - https://www.ncbi.nlm.nih.gov/research/bionlp/Tools/gnormplus/
- - https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/GNormPlus/GNormPlusCorpus.zip

**Comment by mcullan** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @mcullan, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins). I recognize you *just* signed up but we are cruising through all the issues and checking in : )

**Comment by mcullan** [comment]
@hakunanatasha I'm still working on these and expect to finish them this weekend. Thanks for making this all possible!

**Comment by hakunanatasha** [comment]
@mcullan sounds awesome, ping me so i can have the fun of reviewing it! I'm excited to see your submission 🌸

**Comment by hakunanatasha** [comment]
Closes with #118

**Comment by sg-wbi** [comment]
I am reopening this because #118 handles only a part of the dataset although it is shipped with the same zip file.
