### ISSUE TITLE
Create dataset loader for Citation GIA Test Collection

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#118]
- Task: NER, NEN
- License: ? ("freely available from website")
- Format: BioC/PubTattor
- Language: English
- Citation:
Wei C-H, Kao H-Y, Lu Z. GNormPlus: An Integrative Approach for Tagging Gene, Gene Family and Protein Domain. BioMed Research International Journal, Text Mining for Translational Bioinformatics special issue, BioMed Research International Journal, Article ID 918710; DOI: dx.doi.org/10.1155/2015/918710 (2015)

- Source: 
- - https://www.ncbi.nlm.nih.gov/research/bionlp/Tools/gnormplus/
- - https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/GNormPlus/GNormPlusCorpus.zip

**Comment by marianna13** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @marianna13, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins); I recognize you *juuuust* assigned yourself but I am just cruising through all the issues to check in : )

**Comment by marianna13** [comment]
Hi! Yes, I'm working on the loader script for this dataset. By the way, I have encountered a problem: can you, please, tell me which database should I use for the normalization in entities? If I should use any😊
