### ISSUE TITLE
Create dataset loader for ProGene

### ISSUE THREAD

**Issue by leonweber** [bigscience-workshop/biomedical#120]
Task: NER

License: ???

Format: custom

Language: English

Citation: @InProceedings{Faessler2020,
  author    = {Erik Faessler and Luise Modersohn and Christina Lohr and Udo Hahn},
  booktitle = {Proceedings of The 12th Language Resources and Evaluation Conference, {LREC} 2020, Marseille, France, May 11-16, 2020},
  title     = {ProGene - {A} Large-scale, High-Quality Protein-Gene Annotated Benchmark Corpus},
  year      = {2020},
  editor    = {Nicoletta Calzolari and Fr{\'{e}}d{\'{e}}ric B{\'{e}}chet and Philippe Blache and Khalid Choukri and Christopher Cieri and Thierry Declerck and Sara Goggi and Hitoshi Isahara and Bente Maegaard and Joseph Mariani and H{\'{e}}l{\`{e}}ne Mazo and Asunci{\'{o}}n Moreno and Jan Odijk and Stelios Piperidis},
  pages     = {4585--4596},
  publisher = {European Language Resources Association},
  bibsource = {dblp computer science bibliography, https://dblp.org},
  biburl    = {https://dblp.org/rec/conf/lrec/FaesslerMLH20.bib},
  url       = {https://aclanthology.org/2020.lrec-1.564/},
}

Source: https://zenodo.org/record/3698568#.Yg5vIS9XZ0I

**Comment by abhinavkashyap** [comment]
#self-assign

**Comment by abhinavkashyap** [comment]
Hi any update on merging these? I saw in discord that you mentioned that this dataset is open still

**Comment by jason-fries** [comment]
Hi @abhinavkashyap 
We're working on the backlog now ! Thanks for checking in, we'll followup shortly
