### ISSUE TITLE
Test set bioasq9b too small

### ISSUE THREAD

**Issue by nomisto** [bigscience-workshop/biomedical#134]
## Describe the bug

(I hope this is the right place to report dataset specific bugs)
There is a bug in the code for the concatenation of the multiple test files to one single file of bioasq9b.

https://github.com/bigscience-workshop/biomedical/blob/a59a21dea6d3a13753a166058d10c29b55014188/examples/bioasq9b.py#L167-L181

Line 180: Should be `json.dump(test_data, open(test_fpath, "wt"))`

## Steps to reproduce the bug
```python
from datasets import load_dataset
ds = load_dataset("examples/bioasq9b.py", "bigbio")
print(ds)
```

## Expected results

```
DatasetDict({
    train: Dataset({
        features: ['id', 'document_id', 'question_id', 'question', 'type', 'context', 'answer'],
        num_rows: 46130
    })
    test: Dataset({
        features: ['id', 'document_id', 'question_id', 'question', 'type', 'context', 'answer'],
        num_rows: 5712
    })
})
```

## Actual results

```
DatasetDict({
    train: Dataset({
        features: ['id', 'document_id', 'question_id', 'question', 'type', 'context', 'answer'],
        num_rows: 46130
    })
    test: Dataset({
        features: ['id', 'document_id', 'question_id', 'question', 'type', 'context', 'answer'],
        num_rows: 1213
    })
})
```

## Environment info

- `datasets` version: 1.18.3
- Platform: Windows-10-10.0.19042-SP0
- Python version: 3.9.7
- PyArrow version: 7.0.0

**Comment by sunnnymskang** [comment]
@jason-fries
