### ISSUE TITLE
nlmchem: 'source' config does not return anything

### ISSUE THREAD

**Issue by nomisto** [bigscience-workshop/biomedical#135]
## Describe the bug

'source' config of nlmchem does not return anything due to missing `yield` in `_generate_examples` 

## Steps to reproduce the bug

```python
a = load_dataset("examples/nlmchem.py", "source")
print(a)
```

## Expected results

Correct load of source config of dataset.

## Actual results

```bash
DatasetDict({
    train: Dataset({
        features: ['passages'],
        num_rows: 0
    })
    test: Dataset({
        features: ['passages'],
        num_rows: 0
    })
    validation: Dataset({
        features: ['passages'],
        num_rows: 0
    })
})
```

## Environment info

- `datasets` version: 1.18.3
- Platform: Windows-10-10.0.19042-SP0
- Python version: 3.9.7
- PyArrow version: 7.0.0

**Comment by sunnnymskang** [comment]
@sg-wbi
