### ISSUE TITLE
Create dataset loader for Mantra GSC

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#137]
## Adding a Dataset
- **Name:** *Mantra GSC*
- **Description:** *We selected text units from different parallel corpora (Medline abstract titles, drug labels, biomedical patent claims) in English, French, German, Spanish, and Dutch. Three annotators per language independently annotated the biomedical concepts, based on a subset of the Unified Medical Language System and covering a wide range of semantic groups.*
- **Task:** *NER, NED*
- **Paper:** [*A multilingual gold-standard corpus for biomedical concept recognition: the Mantra GSC*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4986661/)
- **Data:** *[https://files.ifi.uzh.ch/cl/mantra/gsc/GSC-v1.1.zip](https://files.ifi.uzh.ch/cl/mantra/gsc/GSC-v1.1.zip)*
- **License:** *[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)*
- **Motivation:** *This is a multilingual, parallel dataset (French, Spanish, Dutch, German, English)*

**Comment by karthikrangasai** [comment]
Hello all,

The dataset has a brat format available, but the `.ann` files have lines starting with `#` which according to the format specification are Annotator Notes. ( [Format Specification](https://brat.nlplab.org/standoff.html) )

But in the examples of the dataset, the Tags seem to be in that very line that starts with `#`.

I am unsure of how to proceed in regards with this and am seeking some help.

Thank you.

![Screenshot from 2022-04-06 19-46-09](https://user-images.githubusercontent.com/39360170/162000295-0d552939-a327-4626-a3ff-3c673f3426d7.png)

**Comment by hakunanatasha** [comment]
@leonweber @jason-fries @galtay @sg-wbi @sunnnymskang @debajyotidatta Pinged some other admins to answer this!

**Comment by leonweber** [comment]
From the paper: The comments correspond to 'CUI, preferred term, semantic type, and semantic group (DISO is “Disorders”)'. These have been all manually verified. My suggestion would be to
* Add support for annotator notes to `utils.parsing.parse_brat`
* Implement 'CUI', 'preferred term', 'semantic type' and 'semantic group' all as separate fields in the `source` schema
* Implement 'semantic group' as entity type in the `bigbio_kb` schema

What do you think @karthikrangasai? Does that sound reasonable?

**Comment by karthikrangasai** [comment]
Hello @leonweber ,

Sorry for the late reply.
Sure, I can try to add this and get it working. Will need some help here and there. Will take help through the discord server maybe.

Thank you providing these tips.

**Comment by hakunanatasha** [comment]
Hi @karthikrangasai no worries at all; feel free to ping us anytime by summoning the @admin command!
