### ISSUE TITLE
Create dataset loader for PharmaCoNER

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#138]
## Adding a Dataset
- **Name:** *PharmaCoNER*
- **Description:** *Following the outline of previous chemical and drug NER efforts, in particular the BioCreative CHEMDNER tracks, we organize the first task on chemical and drug mention recognition from Spanish medical texts, namely from a corpus of Spanish clinical case studies.*
- **Task:** *NER, NED*
- **Paper:** *[PharmaCoNER: Pharmacological Substances, Compounds and proteins Named Entity Recognition track](https://aclanthology.org/D19-5701/)*
- **Data:** *[Challenge Homepage](https://temu.bsc.es/pharmaconer/index.php/datasets/)*
- **License:** *[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)*
- **Motivation:** *Spanish langauge dataset*

**Comment by mapama247** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @mapama247, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by mapama247** [comment]
Hi @hakunanatasha! Yes, I have not finished yet but I plan to do it before the deadline. I already had a script that could load the dataset from local conll files, but on the Discord channel I was told that it is preferable to have a data loader that directly downloads and converts the brat files from the official site... so I will need some extra time to change this :)

**Comment by hakunanatasha** [comment]
@mapama247 no worries, feel free to ping me if you need help with this change!
