### ISSUE TITLE
Create a dataset loader for BioNLP-ST 2011 GE

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#145]
## Adding a Dataset
- **Name:** *BioNLP-ST 2011 GE*
- **Task:** *Event extraction*
- **Paper:** *[link to the dataset paper if available](https://aclanthology.org/W11-1802.pdf)*
- **Data:** *[link to the Github repository or current dataset location](https://github.com/openbiocorpora/bionlp-st-2011-ge)*
- **License:** *License Terms for BioNLP Shared Task 2011 Data*
- original link: https://sites.google.com/site/bionlpst/bionlp-shared-task-2011/genia-event-extraction-genia

**Comment by barthfab** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
@barthfab let us know if you need help
