### ISSUE TITLE
Create a dataset loader for BioNLP-ST 2013 GE

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#146]
## Adding a Dataset
- **Name:** *BioNLP-ST 2013 GE*
- **Task:** *Event extraction*
- **Paper:** *[link to the dataset paper if available](https://aclanthology.org/W13-2002.pdf)*
- **Data:** *[link to the Github repository or current dataset location](https://github.com/openbiocorpora/bionlp-st-2013-ge)*
- **License:** *License Terms for BioNLP Shared Task 2013 Data*
- original link: https://sites.google.com/site/bionlpst2013/

**Comment by jason-fries** [comment]
Hi @barthfab can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**. No worries if you are not finished but still intend to work on this!
