### ISSUE TITLE
Create dataset loader for BioNLP-ST 2013 PC

### ISSUE THREAD

**Issue by leonweber** [bigscience-workshop/biomedical#148]
- **Name:** BioNLP-ST 2013 PC
- **Description:** Event extraction data set for pathway curation
- **Task:** Event extraction
- **Paper:** https://aclanthology.org/W13-2009.pdf
- **Data:** [https://github.com/openbiocorpora/bionlp-st-2013-pc]()
- **License:** License Terms for BioNLP Shared Task 2013 Data

**Comment by barthfab** [comment]
#self-assign
