### ISSUE TITLE
Create dataset loader for JNLPBA

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#15]
From http://www.geniaproject.org/shared-tasks/bionlp-jnlpba-shared-task-2004

**Comment by benjaminbeilharz** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @benjaminbeilharz, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by hakunanatasha** [comment]
@benjaminbeilharz let me know on discord; thank you! please ping me if you need help.

**Comment by abhinavkashyap** [comment]
Is it still being worked upon?? Else I would like to work on this

**Comment by benjaminbeilharz** [comment]
@abhinavkashyap please go ahead!

**Comment by abhinavkashyap** [comment]
@benjaminbeilharz Thanks.. Will send a PR soon :)

**Comment by CallumMcMahon** [comment]
The license attached to the download files is as follows
```
4. Licence terms

Use and distribution of abstracts drawn from PubMed is subject to the
PubMed(R) license terms as stated in Clause 1.

Use and distribution of full texts is subject to the license terms
applying to each publication.

Annotations created by the GENIA Project are licensed under the
Creative Commons Attribution 3.0 Unported License. To view a copy of
this license, visit http://creativecommons.org/licenses/by/3.0/ or
send a letter to Creative Commons, 444 Castro Street, Suite 900,
Mountain View, California, 94041, USA.

Annotations created by the GENIA Project must be attributed as
detailed in Clause 5.
```

Is there a reason it's marked as CC BY NC 3.0 instead of CC BY 3.0?

**Comment by jason-fries** [comment]
@CallumMcMahon Nice catch! It's probable that we copied over some other GENIA licence with different terms. In this next phase of the hackathon, we're discussing how to better track provenance of licensing files to prevent confusion and errors.

**Comment by jason-fries** [comment]
@abhinavkashyap 
Checking to see if you are still working on this dataset. If so, please push a PR as soon as possible. Let us know how we can help!

**Comment by abhinavkashyap** [comment]
Hi! I just checked and found this on Huggingface datasets https://huggingface.co/datasets/jnlpba
Do you want me to continue to work on this?

**Comment by jason-fries** [comment]
@abhinavkashyap  Yup!
- You can use the existing implementation to see if it accurately implements the `source` schema (sometimes implementations in the hub don't reflect the source schema accurately!) 
- Implement the `bigbio` schema view

**Comment by benjaminbeilharz** [comment]
#self-assign
