### ISSUE TITLE
Create dataset loader for BioNLP-ST 2011 ID

### ISSUE THREAD

**Issue by leonweber** [bigscience-workshop/biomedical#150]
- **Name:** BioNLP-ST 2011 ID
- **Description:** Event extraction related to infectious diseases
- **Task:** Event Extraction
- **Paper:** https://aclanthology.org/W11-1804.pdf
- **Data:** [https://github.com/openbiocorpora/bionlp-st-2011-id]()
- **License:** License Terms for BioNLP Shared Task 2011 Data

**Comment by barthfab** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @barthfab can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**. No worries if you are not finished but still intend to work on this!
