### ISSUE TITLE
Create dataset loader for Bio-SimVerb

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#153]
- **Name:** Bio-SimVerb
- **Description:** Verb pairs with similarity scores
- **Task:** Semantic Similarity
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2039-z
- **Data:** https://github.com/cambridgeltl/bio-simverb/tree/master/wvlib/word-similarities/bio-simverb
- **License:** ?
- **Motivation:** Evaluation

**Comment by debajyotidatta** [comment]
#self-assign

**Comment by tanmaylaud** [comment]
@debajyotidatta If you haven't started work on this, can I pick it up instead?

**Comment by debajyotidatta** [comment]
@tanmaylaud : Hey, can you finish all the ones you have already signed up for? One you are done, ping back here! That was no dataset is being held up.

**Comment by tanmaylaud** [comment]
@debajyotidatta  the issue is that in the others that I have signed up, the data is not public so Jason asked me to check other ones.

**Comment by debajyotidatta** [comment]
@tanmaylaud : So I had already implemented this (just pushed the PR) but are you actually out of datasets? Let me take a look at it! I am sure we will be able to find something for you.
