### ISSUE TITLE
Create dataset loader for Bio-SimLex

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#154]
- **Name:** Bio-SimLex
- **Description:** Noun pairs with similarity scores
- **Task:** Semantic Similarity
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2039-z
- **Data:** https://github.com/cambridgeltl/bio-simverb/tree/master/wvlib/word-similarities/bio-simlex
- **License:** ?
- **Motivation:** Evaluation

**Comment by debajyotidatta** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hey @debajyotidatta let us know if you have bandwidth to implement this. Otherwise we'll release back into the pool!

**Comment by tanmaylaud** [comment]
#self-assign

**Comment by debajyotidatta** [comment]
Hi, @jason-fries : I will be done with it by Monday

**Comment by hakunanatasha** [comment]
@debajyotidatta @tanmaylaud can you confirm who is working on this I only see @tanmaylaud assigned.

**Comment by debajyotidatta** [comment]
@tanmaylaud Just noticing your comment! Feel free to do this. So glad you are part of this.

@hakunanatasha : if by any chance @tanmaylaud can't complete or doesn't get bandwidth I can do this later.

**Comment by tanmaylaud** [comment]
@hakunanatasha @jason-fries the label in this dataset is raw float value (0-10). This does not fit in our bio pairs schema. Please advise.

**Comment by hakunanatasha** [comment]
@tanmaylaud can you ping @debajyotidatta since he may have already implemented this.

**Comment by debajyotidatta** [comment]
@tanmaylaud : go for it! If you get stuck ping me.

**Comment by tanmaylaud** [comment]
@debajyotidatta I have implemented most of the script except the label part. Are we supposed to apply a threshold on the float value to make it a string label ?

**Comment by debajyotidatta** [comment]
Hi, for the source schema keep the original. For the bigbio schema apply thresholding.

**Comment by galtay** [comment]
made some comments on #406
