### ISSUE TITLE
Create dataset loader for UMNSRS Reference Standard

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#155]
- **Name:** UMNSRS Reference Standard
- **Description:** UMNSRS, developed by Pakhomov, et al., consists of 725 clinical term pairs whose semantic similarity and relatedness. 
- **Task:** Semantic Similarity
- **Paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3041430/
- **Data:** https://nlp.cs.vcu.edu/data.html#umnsrs
- **License:** ?
- **Motivation:** Evaluation

**Comment by trishalaneeraj** [comment]
#self-assign

**Comment by trishalaneeraj** [comment]
Still working on this!

**Comment by jason-fries** [comment]
Thanks!
