### ISSUE TITLE
Create dataset loader for MSH-WSD dataset 

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#156]
- **Name:** MSH-WSD Dataset
- **Description:** 
- **Task:** Word Sense Disambiguation
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-223
- **Data:** https://lhncbc.nlm.nih.gov/ii/areas/WSD/collaboration.html
- **License:** ?
- **Motivation:** completeness. but this one looks hard.

**Comment by tanmaylaud** [comment]
#self-assign

**Comment by tanmaylaud** [comment]
this dataset requires access to nlm. I have requested for it but it will take time.

**Comment by jason-fries** [comment]
Hi @tanmaylaud 
Thanks for the update. If you don't have current access it might be best to free up this (and other) datasets and volunteer for some other open datasets. Let us know if we can help in anyway!

**Comment by tanmaylaud** [comment]
@jason-fries I don't see any open issues that have publicly available datasets. Please feel free to tag me in anything that's doable.

**Comment by jason-fries** [comment]
@tanmaylaud id check back on Sunday and see if any datasets have opened up again. Also, if you know of any great biomedical NLP datasets we missed, you can suggest and volunteer for that dataset :)

**Comment by nomisto** [comment]
#self-assign

**Comment by nomisto** [comment]
@hakunanatasha That's the second one. I realized i've included instructions as a comment block. Should I put it into the docstring of the script?
