### ISSUE TITLE
Create dataset loader for NLM-WSD Dataset

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#157]
- **Name:** NLM-WSD dataset
- **Description:** 100 randomly selected instances of 50 frequent and highly ambiguous words from 1998 MEDLINE abstracts. 
- **Task:** Word Sense Disambiguation
- **Paper:** https://pubmed.ncbi.nlm.nih.gov/11825285/
- **Data:** https://lhncbc.nlm.nih.gov/restricted/ii/areas/WSD/index.html
- **License:** ? 
- **Motivation:** completeness, but this looks hard.

**Comment by tanmaylaud** [comment]
#self-assign

**Comment by tanmaylaud** [comment]
this data requires access to nlm. I have requested for it but it will take time.

**Comment by hakunanatasha** [comment]
Hi @tanmaylaud sometimes data access issues may take a while; I'd recommend perhaps implementing a dataloader that has a public license (I think you have a few other datasets assigned).

**Comment by tanmaylaud** [comment]
@hakunanatasha even the other WSD dataset requires similar access. I am looking for 3 datasets to satisfy the contribution criteria. Currently, I have only 2 that are publicly available. Thanks for your help!

**Comment by nomisto** [comment]
#self-assign

**Comment by nomisto** [comment]
@hakunanatasha Tagged you as discussed on discord :)
