### ISSUE TITLE
Create dataset loader for MayoSRS Reference Standard

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#161]
- **Name:** MayoSRS Reference Standard
- **Description:** MayoSRS consists of 101 clinical term pairs whose relatedness was determined by nine medical coders and three physicians from the Mayo Clinic. 
- **Task:** Semantic Similarity
- **Paper:** https://pubmed.ncbi.nlm.nih.gov/16875881/
- **Data:** https://nlp.cs.vcu.edu/data.html#mayosrs
- **License:** ?
- **Motivation:**

**Comment by trishalaneeraj** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @trishalaneeraj  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by trishalaneeraj** [comment]
Hi @jason-fries, I'm still working on this
