### ISSUE TITLE
Create dataset loader for BioASQ Task B (2014-2021)

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#17]
From http://participants-area.bioasq.org/general_information/Task9b/

**Comment by sunnnymskang** [comment]
@jason-fries running unit tests seems to be failing  on 4b_bigbio_schema - Would you mind taking a look at this?

**Comment by galtay** [comment]
I get a few globally_unique_id test fails on my end too when running the tests now

**Comment by hakunanatasha** [comment]
Seems like we have some updated version in the datasets; closing for now
