### ISSUE TITLE
Create dataset loader for BioNLP-ST 2013 CG

### ISSUE THREAD

**Issue by WojciechKusa** [bigscience-workshop/biomedical#171]
## Adding a Dataset
- **Name:** *BioNLP-ST 2013 CG*
- **Description:** *Event extraction data set for Cancer Genetics*
- **Task:** *Event extraction*
- **Paper:** *https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4511510*
- **Data:** *https://github.com/openbiocorpora/bionlp-st-2013-cg*
- **License:** *[CC BY-SA 3.0](https://github.com/openbiocorpora/bionlp-st-2013-pc/blob/master/LICENSE)*

**Comment by jason-fries** [comment]
Hi @barthfab can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!
