### ISSUE TITLE
Create dataset loader for CADEC

### ISSUE THREAD

**Issue by WojciechKusa** [bigscience-workshop/biomedical#172]
## Adding a Dataset
- **Name:** *CADEC*
- **Description:** *CSIRO Adverse Drug Event Corpus (CADEC) is a new rich annotated corpus of medical forum posts on patient-reported Adverse Drug Events (ADEs).*
- **Task:** *NER, RE*
- **Paper:** *https://www.sciencedirect.com/science/article/pii/S1532046415000532*
- **Data:** *https://data.gov.au/dataset/ds-dap-csiro%3A10948/details?q=*
- **License:** *[CSIRO Data License (Non-commercial)](https://confluence.csiro.au/display/dap/CSIRO+Data+Licence)*

**Comment by nomisto** [comment]
#self-assign

**Comment by masapasa** [comment]
I cant find the cadec dataset on huggingface
