### ISSUE TITLE
Create dataset loader for EBM PICO

### ISSUE THREAD

**Issue by WojciechKusa** [bigscience-workshop/biomedical#175]
## Adding a Dataset
- **Name:** *EBM PICO*
- **Description:** *This corpus release contains 4,993 abstracts annotated with (P)articipants, (I)nterventions, and (O)utcomes. Training labels are sourced from AMT workers and aggregated to reduce noise. Test labels are collected from medical professionals.*
- **Task:** *NER*
- **Paper:** *https://aclanthology.org/P18-1019/*
- **Data:** *https://github.com/bepnye/EBM-NLP*
- **License:** *?*
- **Motivation:** *PICO extraction dataset*

**Comment by WojciechKusa** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @WojciechKusa 
Did you still want to implement this dataset or can we add it back to the pool of available datasets?

**Comment by WojciechKusa** [comment]
Yes, I am still working on it. I will be ready for Thursday.
