### ISSUE TITLE
Create dataset loader for BioCreative II: Gene Mention Task 

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#18]
From https://github.com/spyysalo/bc2gm-corpus/raw/master/conll/

**Comment by benjaminbeilharz** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @benjaminbeilharz, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by hakunanatasha** [comment]
@sg-wbi I think @benjaminbeilharz may not get to work on this till April 11; if it does, let's remember to close the issue.

**Comment by benjaminbeilharz** [comment]
@hakunanatasha @sg-wbi is right. The dataset has been done under a different issue. Can be closed :)

**Comment by hakunanatasha** [comment]
@benjaminbeilharz @sg-wbi closing issue as it's superceded by another dataset that combines the information.
