### ISSUE TITLE
unittests pass- nlm chem 

### ISSUE THREAD

**Issue by sunnnymskang** [bigscience-workshop/biomedical#199]
## Describe the bug
Running unit tests on nlmchem generates warning msgs in checking offsets - please make sure this is error coming from dataset not dataset loader

## Steps to reproduce the bug
``` python -m tests.test_bigbio examples/nlmchem.py     
```

## Actual results
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Number of texts 1 != number of offsets 0. Please make sure that this error already exists in the original data and was not introduced in the data loader.
WARNING:__main__:Example:22297 - entity:22286  text:`water` != text_by_offset:` wate`

There are features with wrong offsets! This is not a hard failure, as it is common for this type of datasets. However, if the error list is long (e.g. >10) you should double check your code.
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets

**Comment by sunnnymskang** [comment]
@sg-wbi

**Comment by hakunanatasha** [comment]
fixed with PR #205
