### ISSUE TITLE
unit tests - bc5cdr

### ISSUE THREAD

**Issue by sunnnymskang** [bigscience-workshop/biomedical#200]
## Describe the bug
running unit tests on bc5cdr produces warning msgs on offsets and reference elements - make sure that this is not due to dataset loader

## Steps to reproduce the bug
``` python -m tests.test_bigbio examples/bc5cdr.py    
```
## Actual results
Example:5983 - entity:5996  text:`` != text_by_offset:`e antigen`
Example:6730 - entity:6746  text:`aortic regurgitation` != text_by_offset:`aortic`
Example:6730 - entity:6746  text:`` != text_by_offset:`regurgitation`
Example:7197 - entity:7209  text:`hematologic disorder` != text_by_offset:`hematologic`
Example:7197 - entity:7209  text:`` != text_by_offset:`disorder`
Example:7803 - entity:7810  text:`haematological toxicities` != text_by_offset:`haematological`
Example:7803 - entity:7810  text:`` != text_by_offset:`toxicities`
Example:7803 - entity:7811  text:`renal toxicities` != text_by_offset:`renal`
Example:7803 - entity:7811  text:`` != text_by_offset:`toxicities`
Example:7803 - entity:7812  text:`hepatic toxicities` != text_by_offset:`hepatic`
Example:7803 - entity:7812  text:`` != text_by_offset:`toxicities`
Example:8357 - entity:8363  text:`detrimental effect on cognition` != text_by_offset:`detrimental effect on`
Example:8357 - entity:8363  text:`` != text_by_offset:`cognition`
Example:8679 - entity:8684  text:`bladder tumours` != text_by_offset:`bladder`
Example:8679 - entity:8684  text:`` != text_by_offset:`tumours`
Example:10089 - entity:10107  text:`hematological toxicities` != text_by_offset:`hematological`
Example:10089 - entity:10107  text:`` != text_by_offset:`toxicities`
Example:10262 - entity:10269  text:`impaired memory` != text_by_offset:`impaired`
Example:10262 - entity:10269  text:`` != text_by_offset:`memory`
Example:10367 - entity:10376  text:`decrease of heart rate (HR)` != text_by_offset:`decrease of`
Example:10367 - entity:10376  text:`` != text_by_offset:`heart rate (HR)`
Example:10367 - entity:10381  text:`decrease of HR` != text_by_offset:`decrease of`
Example:10367 - entity:10381  text:`` != text_by_offset:`HR`
Example:10367 - entity:10388  text:`decrease of HR` != text_by_offset:`decrease of`
Example:10367 - entity:10388  text:`` != text_by_offset:`HR`
Example:10643 - entity:10652  text:`arterial thromboemboli` != text_by_offset:`arterial`
Example:10643 - entity:10652  text:`` != text_by_offset:`thromboemboli`
Example:11023 - entity:11040  text:`hemorrhagic complications` != text_by_offset:`hemorrhagic`
Example:11023 - entity:11040  text:`` != text_by_offset:`complications`
Example:11283 - entity:11289  text:`acute pain` != text_by_offset:`acute`
Example:11283 - entity:11289  text:`` != text_by_offset:`pain`

There are features with wrong offsets! This is not a hard failure, as it is common for this type of datasets. However, if the error list is long (e.g. >10) you should double check your code.
INFO:__main__:KB ONLY: Checking event offsets
INFO:__main__:KB ONLY: Checking coref offsets

**Comment by jason-fries** [comment]
Fixed in #201
