### ISSUE TITLE
Create dataset loader for AnEM

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#206]
## Adding a Dataset
- **Name:** AnEM
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://aclanthology.org/W12-4304/
- **Data:** http://www.nactem.ac.uk/anatomy/
- **License:** CC BY-SA 3.0

**Comment by s-desh** [comment]
#self-assign

**Comment by s-desh** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @s-desh  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by s-desh** [comment]
Yes @jason-fries, I'm still working on this
