### ISSUE TITLE
Create dataset loader for BioASQ Task C 2017

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#209]
## Adding a Dataset
- **Name:** BioASQ Task C 2017
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://aclanthology.org/W17-2306.pdf
- **Data:** http://participants-area.bioasq.org/general_information/Task5c/
- **License:** NLM License Code: 8283NLM123

**Comment by HallerPatrick** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @HallerPatrick  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by HallerPatrick** [comment]
Still working on it :)

**Comment by jason-fries** [comment]
Thanks!
