### ISSUE TITLE
Create dataset loader for BioCreative II: Gene Normalization (GN)

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#211]
## Adding a Dataset
- **Name:** BioCreative II: Gene Normalization (GN)
- **Description:** *None provided*
- **Task:** NED
- **Paper:** https://link.springer.com/article/10.1186/gb-2008-9-s2-s3
- **Data:** https://biocreative.bioinformatics.udel.edu/resources/corpora/biocreative-ii-corpus/
- **License:** ?

**Comment by giyaseddin** [comment]
#self-assign

**Comment by sg-wbi** [comment]
This might be superseded by #117

**Comment by hakunanatasha** [comment]
@sg-wbi @giyaseddin seems to be superceded by #117 closing the issue for now.
