### ISSUE TITLE
Create dataset loader for GENETAG

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#212]
## Adding a Dataset
- **Name:** GENETAG
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-6-S1-S3
- **Data:** https://github.com/openbiocorpora/genetag
- **License:** Public Domain

**Comment by s-desh** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @s-desh  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by jason-fries** [comment]
Hi @s-desh can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by s-desh** [comment]
Yes @jason-fries, I'm still working on this
