### ISSUE TITLE
Create dataset loader for BioInfer

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#214]
## Adding a Dataset
- **Name:** BioInfer
- **Description:** *None provided*
- **Task:** RE,NER
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-8-50
- **Data:** https://github.com/metalrt/ppi-dataset/tree/master/csv_output
- **License:** ?

**Comment by jason-fries** [comment]
Hi @whoisjones  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by whoisjones** [comment]
Hi @jason-fries, this one is comming today.
