### ISSUE TITLE
Create dataset loader for LLL

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#217]
## Adding a Dataset
- **Name:** LLL
- **Description:** *None provided*
- **Task:** RE,NER
- **Paper:** http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=4B3F165F09189F5487A59C6E0C19C855?doi=10.1.1.96.5066&rep=rep1&type=pdf
- **Data:** http://genome.jouy.inra.fr/texte/LLLchallenge/
- **License:** ?

**Comment by nomisto** [comment]
#self-assign
