### ISSUE TITLE
Create dataset loader for PUBHEALTH

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#218]
## Adding a Dataset
- **Name:** PUBHEALTH
- **Description:** *None provided*
- **Task:** SENT_CLASS
- **Paper:** https://aclanthology.org/2020.emnlp-main.623/
- **Data:** https://github.com/neemakot/Health-Fact-Checking/blob/master/data/DATASHEET.md
- **License:** MIT License

**Comment by sushil-bharati** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @sushil-bharati can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by sidkiblawi** [comment]
Is @sushil-bharati still working on this? I can take it if they don't have the bandwidth.

**Comment by hakunanatasha** [comment]
@sidkiblawi assigning you to this
