### ISSUE TITLE
Create dataset loader for n2c2 2006 - Deidentification

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#219]
## Adding a Dataset
- **Name:** n2c2 2006 - Deidentification
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://academic.oup.com/jamia/article/14/5/550/720189
- **Data:** https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
- **License:** DUA-C/NC

**Comment by jdposada** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @jdposada can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by jdposada** [comment]
hi @jason-fries ,

I am still working on this. Actually working with someone else. How can I give him credit as well?

**Comment by hakunanatasha** [comment]
@jdposada mentioned the details on the other issues!

**Comment by galtay** [comment]
@jdposada feel free to pull from the work in the above PR ... we will make sure everyone involved gets credit.
