### ISSUE TITLE
Create dataset loader for GENIA Term Corpus

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#22]
From http://www.geniaproject.org/genia-corpus/term-corpus

**Comment by hakunanatasha** [comment]
Hi @sugatoray, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by hakunanatasha** [comment]
Hi @sugatoray thank you!

**Comment by jason-fries** [comment]
@sugatoray  
Checking to see if you are still working on this dataset. If so, please push a PR as soon as possible. Let us know how we can help!

**Comment by sugatoray** [comment]
@jason-fries Thank you. I got caught up in something that delayed my progress on the PRs. Next couple of days will work and ensure these are done lates by Sunday. Could you please extend the deadline to include the PRs until Sunday?

I will also post my questions about respective datasets in their issues, for clarity and quickly finishing them. 

Thank you again for offering to help out.

**Comment by sugatoray** [comment]
I am afraid I will not be able to finish this in time. Unassigned myself.

**Comment by albertvillanova** [comment]
#self-assign
