### ISSUE TITLE
Create dataset loader for n2c2 2014 - Deidentification & Heart Disease

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#220]
## Adding a Dataset
- **Name:** n2c2 2014 - Deidentification & Heart Disease
- **Description:** *None provided*
- **Task:** NER,DOC_CLASS
- **Paper:** https://pubmed.ncbi.nlm.nih.gov/26225918/
- **Data:** https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
- **License:** DUA-C/NC

**Comment by jdposada** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @jdposada can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by jdposada** [comment]
hi @jason-fries ,

I am still working on this. Actually working with someone else. How can I give him credit as well?

**Comment by hakunanatasha** [comment]
@jdposada as mentioned in a different issue with @jason-fries you can opt to either have both your names on the script as co-authors or ideally, your two commit histories tied to two separate GitHub accounts. We are fine with either option.

**Comment by jdposada** [comment]
New PR linked only for the deid task

https://github.com/bigscience-workshop/biomedical/pull/644

**Comment by jdposada** [comment]
New PR linked for the risk factors task 

https://github.com/bigscience-workshop/biomedical/pull/646

**Comment by hakunanatasha** [comment]
merged in datasets
