### ISSUE TITLE
Create dataset loader for n2c2 2018 - Clinical Trial Cohort Selection

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#221]
## Adding a Dataset
- **Name:** n2c2 2018 - Clinical Trial Cohort Selection
- **Description:** *None provided*
- **Task:** DOC_CLASS
- **Paper:** https://academic.oup.com/jamia/article-abstract/26/11/1163/5575392?redirectedFrom=fulltext
- **Data:** https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
- **License:** DUA-C/NC

**Comment by sushil-bharati** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @sushil-bharati  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by singhay** [comment]
#self-assign
