### ISSUE TITLE
Create dataset loader for PubTator Central

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#222]
## Adding a Dataset
- **Name:** PubTator Central
- **Description:** *None provided*
- **Task:** NER,NED,COREF
- **Paper:** https://academic.oup.com/nar/article/47/W1/W587/5494727
- **Data:** https://ftp.ncbi.nlm.nih.gov/pub/lu/PubTatorCentral/
- **License:** Public Domain

**Comment by JohnGiorgi** [comment]
#self-assign

**Comment by JohnGiorgi** [comment]
Hi! 

I have made pretty good progress on this today. I've already had some back and forth with @hakunanatasha in the discord (thank you! it was very helpful) but just wanted to follow up with a few things:

1. I originally said that the dataset came in two flavours: full text + annotations and just annotations. I was mistaken, its actually full text + annotations or title/abstract + annotations. I guess we should still go for the latter right, as the former is 100s of GBs? I am planning to load the text as `dataset.Value("string")` with keys `"title"` and `"abstract"`.
2. There is no parser for pubtator-style annotations, so I rolled my own. I am wondering if it would be useful to add it to `parsing`? I know some other datasets use a pubtator-style format like this, e.g. [BC5CDR](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4860626/), (although in that case it also comes in BioC format). I have included the parser below

```python
def parse_pubtator(filepath: str):
    with open(filepath, "r") as f:
        line = f.readline().strip()
        while line != "":
            if re.search(r"\d+\|t\|", line) is not None:
                pmid, title = line.split("|t|")
                # The next line has to be the abstract.
                abstract = f.readline().split("|a|")[-1].strip()
                line = f.readline().strip()
                mentions = []
                while line != "":  # TODO: I don't know if this works
                    split_line = line.split("\t")
                    if len(split_line) == 6:
                        _, start, end, text, type_, concept_id = split_line
                    # This entity is not grounded. Assign default id of -1.
                    else:
                        _, start, end, text, type_ = split_line
                        concept_id = -1

                    mentions.append(
                        {
                            "concept_id": concept_id,
                            "type": type_,
                            "text": text,
                            "offsets": [int(start), int(end)]
                        }
                    )
                    line = f.readline().strip()
                yield {"pmid": pmid, "title": title, "abstract": abstract, "mentions": mentions}
                line = f.readline().strip()

filepath = "path/to/bioconcepts2pubtatorcentral.offset"
g = parse_pubtator(filepath)
print(next(g))
```
