### ISSUE TITLE
Create dataset loader for BioScope

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#223]
## Adding a Dataset
- **Name:** BioScope
- **Description:** *None provided*
- **Task:** SPAN_CLASS,SPAN_CLASS,SPAN_CLASS
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-9-S11-S9
- **Data:** https://rgai.inf.u-szeged.hu/node/105
- **License:** Public for Research

**Comment by whoisjones** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @whoisjones can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by whoisjones** [comment]
Hi @jason-fries, yes I Plan to do this one today / tomorrow. 👍
