### ISSUE TITLE
Create dataset loader for CORD-NER

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#226]
## Adding a Dataset
- **Name:** CORD-NER
- **Description:** *None provided*
- **Task:** NER
- **Paper:** https://arxiv.org/abs/2003.12218
- **Data:** https://uofi.box.com/s/k8pw7d5kozzpoum2jwfaqdaey1oij93x
- **License:** ?

**Comment by jason-fries** [comment]
Hi @nbroad1881 can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by hakunanatasha** [comment]
@nbroad1881 alas only admins can mark in progress : ) I'll mark that off for you though
