### ISSUE TITLE
Create dataset loader for MEDIQA 2019 QA

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#228]
## Adding a Dataset
- **Name:** MEDIQA 2019 QA
- **Description:** *None provided*
- **Task:** QA
- **Paper:** https://www.aclweb.org/anthology/W19-5039/
- **Data:** https://github.com/abachaa/MEDIQA2019/tree/master/MEDIQA_Task3_QA
- **License:** ?

**Comment by SamuelCahyawijaya** [comment]
#self-assign

**Comment by SamuelCahyawijaya** [comment]
I create a PR for this dataset [here](https://github.com/bigscience-workshop/biomedical/pull/369).
I think it is still subject to change since the QA format for this dataset is still under discussion.

**Comment by SamuelCahyawijaya** [comment]
For this dataset, there are two train datasets from TREC-2017-LiveQA and Alexa, but both can be used for the shared task without any distinction. Currently, I created 2 train splits namely `train_live_qa` and `train_alexa`. Please let me know if you have a different opinion on the split.

Another idea is to simply combine both training data, and provide labels to distinguish the two data sources.
