### ISSUE TITLE
Create dataset loader for GENIA Relation Corpus

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#23]
From http://www.geniaproject.org/genia-corpus/relation-corpus

**Comment by sugatoray** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @sugatoray,, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by hakunanatasha** [comment]
Hi @sugatoray assuming you are in progress on this too since you responded to my other pings : ) thank you!

**Comment by sugatoray** [comment]
@hakunanatasha I am afraid I may not be able to finish this in time. So, I am assigning myself.

**Comment by albertvillanova** [comment]
#self-assign
