### ISSUE TITLE
Create dataset loader for MedDialog

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#231]
## Adding a Dataset
- **Name:** MedDialog
- **Description:** The MedDialog dataset contains conversations between doctors and patients. It has 1.1 million dialogues in Chinese and 0.26 million dialogues in English
- **Task:** SENT_CLASS
- **Paper:** https://arxiv.org/abs/2004.03329
- **Data:** https://github.com/UCSD-AI4H/Medical-Dialogue-System
- **License:** Public for Research

**Comment by j-chim** [comment]
#self-assign
