### ISSUE TITLE
Create dataset loader for ParaMed

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#232]
## Adding a Dataset
- **Name:** ParaMed
- **Description:** *None provided*
- **Task:** TRANSL
- **Paper:** https://arxiv.org/abs/2005.09133
- **Data:** https://github.com/boxiangliu/ParaMed
- **License:** ?

**Comment by benjaminbeilharz** [comment]
#self-assign

**Comment by benjaminbeilharz** [comment]
@jason-fries this was already done.

**Comment by jason-fries** [comment]
Sorry about that @benjaminbeilharz! Thanks for reminding us 😅
