### ISSUE TITLE
Create dataset loader for Evidence-Infer-Treatment

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#234]
## Adding a Dataset
- **Name:** Evidence-Infer-Treatment
- **Description:** *None provided*
- **Task:** SENT_CLASS
- **Paper:** https://arxiv.org/abs/2005.04177
- **Data:** https://github.com/jayded/evidence-inference
- **License:** MIT License

**Comment by jason-fries** [comment]
Hi @cakiki   can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by cakiki** [comment]
Still working on this one @jason-fries :smiley:

**Comment by jason-fries** [comment]
Awesome -- thanks @cakiki !

**Comment by MFreidank** [comment]
#self-assign

**Comment by benjaminbeilharz** [comment]
#self-assign

**Comment by benjaminbeilharz** [comment]
@jason-fries Just filed a PR: https://github.com/bigscience-workshop/biomedical/pull/590
