### ISSUE TITLE
Create dataset loader for BioNLP-ST 2013 BB

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#238]
## Adding a Dataset
- **Name:** BioNLP-ST 2013 BB
- **Description:** *None provided*
- **Task:** NER|RE
- **Paper:** https://aclanthology.org/W13-2024.pdf
- **Data:** http://2013.bionlp-st.org/tasks
- **License:** DUA

**Comment by mrm8488** [comment]
I can do it #self-assigne

**Comment by jason-fries** [comment]
Hi @mrm8488   can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by barthfab** [comment]
@jason-fries I'm not sure if the Dataset exists anymore.
