### ISSUE TITLE
Create dataset loader for BioNLP-ST 2013 GRN

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#239]
## Adding a Dataset
- **Name:** BioNLP-ST 2013 GRN
- **Description:** *None provided*
- **Task:** EE
- **Paper:** https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-16-S10-S1
- **Data:** http://2013.bionlp-st.org/tasks
- **License:** DUA

**Comment by sahil280114** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @sahil280114   can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by SamuelCahyawijaya** [comment]
Hi @jason-fries, CMIIW, I checked the website for this task, but there is no download link to the dataset. Also, the dataset doesn't exist on the [openbicorpora](https://github.com/openbiocorpora). Should we consider skipping this dataset?

[BioNLP-ST 2013 page](https://2013.bionlp-st.org/tasks)
[GRN task page]https://2013.bionlp-st.org/tasks/gene-regulation-network-grn

**Comment by jason-fries** [comment]
Thanks for he heads up. We'll note this dataset is no longer available.

**Comment by hakunanatasha** [comment]
@jason-fries can we close this issue if so?
