### ISSUE TITLE
Create dataset loader for BioNLP-ST 2011 BB

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#240]
## Adding a Dataset
- **Name:** BioNLP-ST 2011 BB
- **Description:** *None provided*
- **Task:** COREF|RE
- **Paper:** https://aclanthology.org/W11-1809.pdf
- **Data:** http://2011.bionlp-st.org/tasks
- **License:** DUA

**Comment by sahil280114** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @sahil280114   can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!
