### ISSUE TITLE
Create dataset loader for MEDDOCAN

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#245]
## Adding a Dataset
- **Name:** MEDDOCAN
- **Description:** *None provided*
- **Task:** NER
- **Paper:** http://ceur-ws.org/Vol-2421/MEDDOCAN_overview.pdf
- **Data:** https://temu.bsc.es/meddocan/index.php/datasets/
- **License:** ?

**Comment by mapama247** [comment]
#self-assign

**Comment by jdposada** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @mapama247  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by hakunanatasha** [comment]
@mapama247 is working on a few other datasets that they mentioned to us; assuming he's working on this too.

**Comment by mapama247** [comment]
hi! sorry for the delay, I missed this message. A colleague of mine (who actually works in the group that created the MEDDOCAN dataset) is willing to do this data loading script, so if that's okay I'll leave this PR for @tonifuc3m

**Comment by jason-fries** [comment]
Hi @mapama247 and @tonifuc3m 
Just checking in on the status of this dataset. Are you still planning on implementing it? If so, let us know how we can help!
