### ISSUE TITLE
Create dataset loader for PsyTAR

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#246]
## Adding a Dataset
- **Name:** PsyTAR
- **Description:** *None provided*
- **Task:** NER|SENT_CLASS
- **Paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6495095/
- **Data:** https://www.askapatient.com/research/pharmacovigilance/corpus-ades-psychiatric-medications.asp
- **License:** CC BY 4.0

**Comment by danilexn** [comment]
#self-assign

**Comment by danilexn** [comment]
This dataset is behind a "store page". Links (with a 48 h expiration period) are generated only after putting an email address.

Should I consider it as local?

**Comment by galtay** [comment]
I would consider it local yes. In general, if we can't get a reproducible download using the `dl_manager` object, we should treat it as local.
