### ISSUE TITLE
Create dataset loader for ContextD Corpus

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#247]
## Adding a Dataset
- **Name:** ContextD Corpus
- **Description:** Erasmus Medical Center (EMC) Dutch clinical corpus annotated for the three contextual properties negation, temporality, and experiencer
- **Task:** SENT_CLASS
- **Paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4264258/#CR28
- **Data:** https://biosemantics.erasmusmc.nl/ContextD/
- **License:** ?

**Comment by clarkpolner** [comment]
I reached out to the Jan Kors for access

**Comment by hakunanatasha** [comment]
@qanastek @clarkpolner  Hi Qanastek and Clark- Please note some datasets may be under licensing agreements which will not allow public access. 

If you find yourself with a dataset that is under strict licensing, please feel free to pick a publicly accessible dataset instead. I know some are restricted to academic sources only.

**Comment by hakunanatasha** [comment]
Just in case - some issues are tagged with labels; these licenses are known. You can look for labels that indicate public licenses (ex: CC or Creative Commons, I think) @jason-fries  @galtay

**Comment by galtay** [comment]
Yes, some datasets are not publicly available and may require data user agreements, documented HIPÅA training, a written proposal detailing how the data will be used ... etc.  It appears that this one specifically asks users to contact Jan for further information (https://biosemantics.erasmusmc.nl/index.php/resources/emc-dutch-clinical-corpus). This looks like a clear case of something that should be implemented as a local dataset and not downloaded in the dataset loader script. 

As @hakunanatasha notes, it might be easier to pick a dataset with a more open license, although those seem to be the first that are claimed :) ... many issues have licenses indicated with tags that you can browse here https://github.com/bigscience-workshop/biomedical/labels

**Comment by FremyCompany** [comment]
I have sent an email to Jan as this dataset is relevant for my research, and I will keep you updated on what reply I get.
