### ISSUE TITLE
Create dataset loader for Pharmacokinetic Corpus

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#250]
## Adding a Dataset
- **Name:** Pharmacokinetic Corpus
- **Description:** *None provided*
- **Task:** SENT_CLASS|DOC_CLASS
- **Paper:** https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122199
- **Data:** http://rweb.compbio.iupui.edu/corpus/downloads.html
- **License:** ?

**Comment by debajyotidatta** [comment]
#self-assign

**Comment by debajyotidatta** [comment]
the data can't be accessed.
![Screen Shot 2022-04-16 at 9 56 44 AM](https://user-images.githubusercontent.com/680145/163677696-165e06ac-8c77-4269-802f-e789eb320513.png)
