### ISSUE TITLE
Create dataset loader for NTCIR-13 MedWeb

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#252]
## Adding a Dataset
- **Name:** NTCIR-13 MedWeb
- **Description:** annotated with 8 symptom labels (such as cold, fever, and flu). Then, participants classify each tweet into 1 of the 2 categories: those containing a patient’s symptom and those that do not
- **Task:** DOC_CLASS|TRANSL
- **Paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6401666/
- **Data:** http://research.nii.ac.jp/ntcir/permission/ntcir-13/perm-en-MedWeb.html
- **License:** CC BY 4.0

**Comment by mdmanurung** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @mdmanurung  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by MFreidank** [comment]
#self-assign

**Comment by MFreidank** [comment]
@jason-fries Can I take this on? Must be implemented as a local dataset, from what I can see (data is available via form), but otherwise seems relatively straightforward. Will ping in case I have any questions.
