### ISSUE TITLE
Create dataset loader for BiologyHowWhyCorpus

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#253]
## Adding a Dataset
- **Name:** BiologyHowWhyCorpus
- **Description:** *None provided*
- **Task:** QA
- **Paper:** https://aclanthology.org/P14-1092/
- **Data:** https://allenai.org/data/biology-how-why-corpus
- **License:** ?

**Comment by j-chim** [comment]
#self-assign

**Comment by nomisto** [comment]
#self-assign
