### ISSUE TITLE
Create dataset loader for BioNLP-ST 2019 Bacteria-Biotope

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#255]
## Adding a Dataset
- **Name:** BioNLP-ST 2019 Bacteria-Biotope
- **Description:** *None provided*
- **Task:** NER|NED|RE
- **Paper:** https://aclanthology.org/D19-5719/
- **Data:** https://sites.google.com/view/bb-2019/dataset
- **License:** ?

**Comment by davidstap** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @davidstap  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by barthfab** [comment]
#self-assign
