### ISSUE TITLE
Create dataset loader for CHEMDNER

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#28]
From http://www.biocreative.org/resources/biocreative-iv/chemdner-corpus/

**Comment by qanastek** [comment]
#self-assign

**Comment by qanastek** [comment]
PR https://github.com/bigscience-workshop/biomedical/pull/292

**Comment by qanastek** [comment]
NEW PR https://github.com/bigscience-workshop/biomedical/pull/304

**Comment by qanastek** [comment]
PR https://github.com/bigscience-workshop/biomedical/pull/326

**Comment by qanastek** [comment]
Merged into Master https://github.com/bigscience-workshop/biomedical/commit/3f280a49af30616aa2d6c53b850ed18da7563e3d
