### ISSUE TITLE
Add dataset loader for NLPMedTerm corpus

### ISSUE THREAD

**Issue by mariosaenger** [bigscience-workshop/biomedical#283]
## Adding a Dataset
- **Name:** *NLPMedTerm*
- **Description:** *A  Spanish clinical trials corpus annotated with UMLS entities*
- **Task:** *NER,NEN*
- **Paper:** *http://www.lllf.uam.es/ESP/nlpdata/wp2/s12911-021-01395-z.pdf*
- **Data:** *http://www.lllf.uam.es/ESP/nlpdata/wp2/CT-EBM-SP.zip*
- **License:** *CC BY-NC 4.0*
- **Motivation:** *Non-english clinical trails corpora are very rare*

**Comment by danilexn** [comment]
#self-assign
