### ISSUE TITLE
Create dataset loader for health-fact

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#29]
From https://github.com/neemakot/Health-Fact-Checking/blob/master/data/DATASHEET.md

**Comment by benjaminbeilharz** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @benjaminbeilharz, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by tanmaylaud** [comment]
#self-assign

**Comment by albertvillanova** [comment]
I think this is a duplicate of:
- #218

CC: @hakunanatasha
