### ISSUE TITLE
Create dataset loader for n2c2 2006 - Smoking Status

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#31]
From https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/

**Comment by bwang482** [comment]
Taking this.

**Comment by hakunanatasha** [comment]
Hi @bwang482 let us know the status : ) I know you've done n2c2 before so ping us if you need help!

**Comment by bwang482** [comment]
Thanks @hakunanatasha ! Will do.
