### ISSUE TITLE
Create dataset loader for n2c2 2008 - Obesity

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#32]
From https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/

**Comment by bwang482** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @bwang482, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins).

Good to see you on the datasets : )

**Comment by bwang482** [comment]
I am @hakunanatasha 
I will get more time to work on this later this week and during the weekends.

**Comment by jason-fries** [comment]
Looks like this dataset was completed and merged from #425 
Closing.
