### ISSUE TITLE
Create dataset loader for GEOKhoj v1

### ISSUE THREAD

**Issue by s-desh** [bigscience-workshop/biomedical#327]
## Adding a Dataset
- **Name:** *GEOKhoj v1*
- **Description:** *Metadata has been extracted for samples from Microarray, Transcriptomics and Single cell experiments which are available on the GEO (Gene Expression Omnibus) database (GEO is a public functional genomics data repository supporting MIAME-compliant data submissions). This dataset contains metadata for 30,000 samples with their respective labels (control/perturbed), which were labelled using the information available in the metadata.*
- **Task:** *TXTCLASS*
- **Paper:** *NA*
- **Data:** *https://github.com/ElucidataInc/GEOKhoj-datasets/tree/main/geokhoj_v1*
- **License:** *[CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)*
- **Motivation:** *With clean and curated metadata for public omics data, people have been able to study drug repurposing, suggest novel drugs for many diseases and explain mechanisms for many approved drugs. In the past, this has been done at a small scale by manually curating public data. But if we want to curate the millions of datasets available publicly we need classifiers trained on high-quality data to curate datasets at scale. GEOKhoj v1 has a large sample of high-quality annotations for public data from GEO with which we can train said classifiers for curation at scale. With this curated dataset we can enable researchers to generate gene signatures at scale which can be used to repurpose a drug, understand the mechanism of a drug, understand a disease and explore normal biological mechanisms.*

**Comment by hakunanatasha** [comment]
@s-desh this is pretty cool - if you feel comfortable implementing it, please go ahead!

**Comment by hakunanatasha** [comment]
It also looks like this is the source paper: https://www.nature.com/articles/ncomms12846

**Comment by s-desh** [comment]
@hakunanatasha Sure. Just fyi, the above mentioned paper was used as a reference and is not the source paper. We at [Elucidata](https://github.com/ElucidataInc) were very inspired by this paper and extended its work by curating 30k samples.

**Comment by s-desh** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Closed with #393
