### ISSUE TITLE
Create dataset loader for n2c2 2009 - Medication

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#33]
From https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/

**Comment by singhay** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
fabulous thank you! Ill assume all datasets with `singhay` will be `in-progress` on the project board

**Comment by jason-fries** [comment]
Incredible. Looking forward to your PR @singhay !
