### ISSUE TITLE
Proposal to add the "Snomed Translation Dictionaries" datasets

### ISSUE THREAD

**Issue by FremyCompany** [bigscience-workshop/biomedical#337]
Hi,

I am author of the following translation corpus:

> **Parallel corpus built with SNOMED CT (by using LaBSE for candidate matching):** This repository provides parallel corpora for medical concepts translation between English (en) and the following languages: Spanish (es); French (fr); Dutch (nl); Danish (da); Swedish (sv);

> https://github.com/FremyCompany/snomed-translate-dictionaries

I see that you are already working on a translation corpus (ParaMed). Would it be interesting if I contributed these dictionaries?

> I hope the paper for this dataset will be published at EAMT this year, but I already talked about this dataset [at CLIN last year](https://www.clin31.ugent.be/programme/#:~:text=SnomedTranslate.nl) as well as at the [2nd Dutch meeting on Dutch Clinical NLP](https://clinical-nlp.cs.ru.nl/#:~:text=SnomedTranslate.nl) but that doesn't do justice to the dataset which is multi-lingual.

Would it be interesting if I contributed these dictionaries?

**Comment by hakunanatasha** [comment]
Hi @FremyCompany has anyone followed up on this or the other issue/dataset you suggested? I think our recommendation is that you are welcome to implement these @leonweber @jason-fries @galtay @sunnnymskang tagged in case I am mis-speaking.

**Comment by hakunanatasha** [comment]
@FremyCompany I'm not sure if someone followed up, but feel free to propose a dataloader for this.
