### ISSUE TITLE
Create dataset loader for n2c2 2010 - Relations

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#38]
From https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/

**Comment by singhay** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @singhay, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)
