### ISSUE TITLE
Create dataset loader for MEDIQA 2019 NLI

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#40]
From https://physionet.org/content/mednli-bionlp19/1.0.1/

**Comment by SamuelCahyawijaya** [comment]
#self-assign

**Comment by SamuelCahyawijaya** [comment]
I am trying to get access to the dataset, but I need to be a credentialed user in physionet.org which might take weeks  to be approved as a credentialed user. Any suggestion?

**Comment by jason-fries** [comment]
Hi @SamuelCahyawijaya,
Thanks for the ping. Sometimes PhysioNet credentialing is fast, but it's hard to estimate here. I would volunteer for another dataset and release this one back into the pool.

**Comment by JohnGiorgi** [comment]
This looks nearly identical to MedNLI, which I just wrote a dataloader for. I could quickly write one for this dataset as well if no one is on it?
