### ISSUE TITLE
Proposal to add BioCreative VII Track 5 LitCovid dataset

### ISSUE THREAD

**Issue by qanastek** [bigscience-workshop/biomedical#400]
## Adding a Dataset
- **Name:** *BioCreative VII Track 5 - LitCovid track Multi-label topic classification for COVID-19 literature annotation*
- **Description:** *The training and development datasets contain the publicly-available text of over 30 thousand COVID-19-related articles and their metadata (e.g., title, abstract, journal). Articles in both datasets have been manually reviewed and articles annotated by in-house models*
- **Task:** *Multi-label classification*
- **Paper:** *https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7778958/*
- **Data:** *https://ftp.ncbi.nlm.nih.gov/pub/lu/LitCovid/biocreative/*
- **License:** *Unknown*
- **Motivation:** *This dataset is one of the biggest multi-labels topic classification dataset on COVID-19 scientific literature.*

**Comment by jason-fries** [comment]
@qanastek Are you volunteering for this dataset?

**Comment by qanastek** [comment]
#self-assign

**Comment by qanastek** [comment]
Yes, I am. I already work on it.

**Comment by jason-fries** [comment]
Amazing -- thank you @qanastek !

**Comment by qanastek** [comment]
Done! PR https://github.com/bigscience-workshop/biomedical/pull/452

**Comment by galtay** [comment]
@qanastek  nice work, I'll review soon!

**Comment by GullyBurns** [comment]
@qanastek Question - is this data different from that put out by NCBI at https://ftp.ncbi.nlm.nih.gov/pub/lu/LitCovid/topic_tagger/ ?

**Comment by qanastek** [comment]
Good question! I checked and none of the `pmid` present in both corpus are shared.

So, It's look like to be more data released aside of the BioCreative event. 

The labels are identical :

```python
['Prevention', 'Diagnosis', 'Treatment', 'Mechanism', 'Transmission', 'Case Report', 'Epidemic Forecasting']
['Prevention', 'Diagnosis', 'Treatment', 'Mechanism', 'Transmission', 'Case Report', 'Epidemic Forecasting']
```

We can create another subset in the corpus or completely create a new dataset loader.

**Comment by qanastek** [comment]
Good question! I checked and none of the `pmid` present in both corpus are shared.

So, It's look like to be more data released aside of the BioCreative event. 

The labels are identical :

```python
['Case Report', 'Diagnosis', 'Epidemic Forecasting', 'Mechanism', 'Prevention', 'Transmission', 'Treatment']
['Case Report', 'Diagnosis', 'Epidemic Forecasting', 'General Info', 'Mechanism', 'Prevention', 'Transmission', 'Treatment']
```

We can create another subset in the corpus or completely create a new dataset loader.
