### ISSUE TITLE
Proposal to add the CAS dataset

### ISSUE THREAD

**Issue by qanastek** [bigscience-workshop/biomedical#419]
## Adding a Dataset
- **Name:** *CAS: French Corpus with Clinical Cases*
- **Description:** *The CAS corpus is build on clinical cases, such as they are reported in the published scientific literature in French. The corpus contain over 397,000 word occurrences, and the existing linguistic and semantic annotations.*
- **Task:** *POS-Tagging & Lemmatization*
- **Paper:** *https://aclanthology.org/W18-5614/*
- **Data:** *http://natalia.grabar.free.fr/resources.php*
- **License:** *Unknown*
- **Motivation:** *This is the only POS-Tagging corpus for clinical cases in french.*

**Comment by giganttheo** [comment]
#self-assign

This dataset is available with the same format as the ESSAI dataset (cf ISSUE #69  ) for which I already proposed a loading script

**Comment by jason-fries** [comment]
Hi @giganttheo 
Just a ping on the status of this dataset. Please let us know if you are still working on it and when you plan to submit a PR. Thanks!!

**Comment by giganttheo** [comment]
Hi @jason-fries I already submitted a PR for this one @ #433 , I think it should work, it's mostly the same code as the one that was already merged for a related task (#423 )

**Comment by sunnnymskang** [comment]
@jason-fries I'm looking into this rn 
@giganttheo sorry for the delay!

**Comment by hakunanatasha** [comment]
Merged in datasets
