### ISSUE TITLE
Create dataset loader for BioRED

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#429]
## Adding a Dataset
- **Name:** *BioRED*
- **Description:** * RE corpus with multiple entity types (e.g., gene/protein, disease, chemical) and relation pairs (e.g., gene-disease; chemical-chemical), on a set of 600 PubMed articles*
- **Task:** *NER, RE*
- **Paper:** *[link to the dataset paper](https://arxiv.org/abs/2204.04263)*
- **Data:** *[link to the Github repository or current dataset location](https://ftp.ncbi.nlm.nih.gov/pub/lu/BioRED/)*
- **License:** *NA*
- **Motivation:** *multiple entity types (e.g., gene/protein, disease, chemical)*

**Comment by qanastek** [comment]
#self-assign

**Comment by shamikbose** [comment]
#self-assign
