### ISSUE TITLE
Create a dataset loader for MeDAL

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#43]
From https://github.com/BruceWen120/medal

**Comment by alisoncallahan** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @alisoncallahan, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)
