### ISSUE TITLE
Proposal to add MedNLI dataset

### ISSUE THREAD

**Issue by tmabraham** [bigscience-workshop/biomedical#438]
## Adding a Dataset
- **Name:** MedNLI - A Natural Language Inference Dataset For The Clinical Domain
- **Description:** A dataset annotated by doctors, performing a natural language inference task), grounded in the medical history of patients.
- **Task:** Natural Language Inference
- **Paper:** https://arxiv.org/abs/1808.06752
- **Data:** https://physionet.org/content/mednli/1.0.0/
- **License:** PhysioNet license
- **Motivation:** A good dataset annotated by clinicians with thousands of sentence pairs.

**Comment by tmabraham** [comment]
@hakunanatasha Until I get PhysioNet access, I will leave this in the public pool for someone else with access to claim...

**Comment by JohnGiorgi** [comment]
I have already wrote 3 dataloaders but I have access to physionet and this dataset looks rather straightforward! I could write this if no one is currently working on it?
