### ISSUE TITLE
Create a dataset loader for MQP - Medical Question Pairs Dataset

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#44]
From https://github.com/curai/medical-question-pair-dataset

**Comment by hakunanatasha** [comment]
example issue already merged

**Comment by nomisto** [comment]
Hi @sunnnymskang , I did some QA on this dataset and I wonder if this is really the homepage of the dataset https://biocreative.bioinformatics.udel.edu/tasks/biocreative-vi/track-5/ ? I did some search and couldn't link the dataset to the homepage, do you know more about this?
