### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'items' - DatasetInfo

### ISSUE THREAD

**Issue by alisoncallahan** [bigscience-workshop/biomedical#449]
I'm trying to test a data loader using

from datasets import load_dataset
data = load_dataset("biodatasets/<dataset_name>/<dataset_name>.py", name="<dataset_name>_bigbio_<schema>")

And getting the error AttributeError: 'tuple' object has no attribute 'items'  pointing to 

return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=features,
            homepage=_HOMEPAGE,
            license=_LICENSE,
            citation=_CITATION,
        )

**Comment by alisoncallahan** [comment]
PR with current version of code is here: https://github.com/bigscience-workshop/biomedical/pull/450

**Comment by galtay** [comment]
the `name` argument in `load_dataset` should be the name of one of the configs for the dataset ... typically config names are something like `<dataset_name>_bigbio_<schema>`

**Comment by alisoncallahan** [comment]
@galtay thanks, I should have included the actual call I was making as an example. thanks to @jason-fries  we fixed the issue (a sneaky trailing comma) and it now works. issue was closed about 3 hours ago.
