### ISSUE TITLE
Create a dataset loader for DDI

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#47]
From https://github.com/isegura/DDICorpus

**Comment by JohnGiorgi** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @JohnGiorgi, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. I think I saw a couple of your discord posts but just checking in : )

**Comment by JohnGiorgi** [comment]
Yes, planning on starting today actually, just need to ask a follow up question in the discord
