### ISSUE TITLE
Create a dataset loader for BioNLP Shared Task 2009

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#48]
From http://www.geniaproject.org/shared-tasks/bionlp-shared-task-2009

**Comment by HallerPatrick** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @HallerPatrick, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this

**Comment by HallerPatrick** [comment]
Still working on it :)

**Comment by jason-fries** [comment]
Thanks @HallerPatrick !
