### ISSUE TITLE
Create a dataset loader for SciCite

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#50]
From https://github.com/allenai/scicite

**Comment by hakunanatasha** [comment]
Hi @stephenbach, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by stephenbach** [comment]
Yup, I plan to work on these. My understanding was that the hackathon goes till the 15th, so I aim to get it in by then. Let me know if that's an issue. Same for #51 #52.

**Comment by hakunanatasha** [comment]
@stephenbach yes of course - this is just for our logistics purposes. Thanks so much, we'll update the progress board. Looking forward to your pr!

**Comment by abhinavkashyap** [comment]
Hi! Is this still worked upon?

**Comment by stephenbach** [comment]
PR work in progress: https://github.com/bigscience-workshop/biomedical/pull/463
