### ISSUE TITLE
Create dataset loader for BEAR

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#501]
## Adding a Dataset
- **Name:** *BEAR*
- **Description:** *A Corpus of Biomedical Entities and Relations on Twitter*
- **Task:** *NER, RE*
- **Paper:** *[link to the dataset paper](https://arxiv.org/abs/2204.09952)*
- **Data:** *[link to the Github repository or current dataset location](https://www.ims.uni-stuttgart.de/en/research/resources/corpora/bioclaim/)*
- **License:** *CC BY-SA license: https://creativecommons.org/licenses/by-sa/4.0/*
- **Motivation:** *It reflects the patient's journey and their subjective perspective on the process of developing symptoms, being diagnosed and offered a treatment, being cured or learning to live with a medical condition*

**Comment by karthikrangasai** [comment]
#self-assign
