### ISSUE TITLE
Proposal to add DisTEMIST

### ISSUE THREAD

**Issue by qanastek** [bigscience-workshop/biomedical#504]
## Adding a Dataset
- **Name:** *DISTEMIST: DISease TExt Mining Shared Task*
- **Description:** *The DisTEMIST corpus is a collection of 1000 clinical cases with disease annotations linked with Snomed-CT concepts. All documents are released in the context of the BioASQ DisTEMIST track for CLEF 2022.*
- **Task:** *Normalization ; NER ; Entity Grounding ; Entity Linking*
- **Paper:** *https://temu.bsc.es/distemist/*
- **Data:** *https://zenodo.org/record/6458455#.YmKeMNpBybg*
- **License:** *Creative Commons Attribution 4.0 International*
- **Motivation:** *It is one of the track for CLEF 2022.*

Data format : `TSV`

**Comment by qanastek** [comment]
_The DISTEMIST organizers will release multilingual resources to foster the development of multilingual tools and generate systems not only for Spanish but also for content in English and Romance languages (French, Portuguese, Italian and Romanian): DISTEMIST-English, DISTEMIST-Italian, DISTEMIST-French, DISTEMIST-Portuguese, DISTEMIST-Catalan and DISTEMIST-Romanian._

**Comment by karthikrangasai** [comment]
#self-assign
