### ISSUE TITLE
Create a dataset loader for miRNA

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#53]
From https://www.scai.fraunhofer.de/en/business-research-areas/bioinformatics/downloads/download-mirna-test-corpus.html

**Comment by qanastek** [comment]
#self-assign

**Comment by qanastek** [comment]
PR https://github.com/bigscience-workshop/biomedical/pull/306

**Comment by qanastek** [comment]
Adding a Dataset
- Name: miRNA
- Description: None provided
- Task: NER
- Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4602280/
- Data: https://www.scai.fraunhofer.de/en/business-research-areas/bioinformatics/downloads/download-mirna-test-corpus.html
- License: Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)
