### ISSUE TITLE
Create a dataset loader for MEDIQA 2019 RQE

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#55]
From https://github.com/abachaa/MEDIQA2019/tree/master/MEDIQA_Task2_RQE

**Comment by SamuelCahyawijaya** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @SamuelCahyawijaya, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by SamuelCahyawijaya** [comment]
Hi @hakunanatasha, sorry for the late reply, I just finished working on it and open a PR [here](https://github.com/bigscience-workshop/biomedical/pull/368).

**Comment by hakunanatasha** [comment]
@SamuelCahyawijaya awesome!
