### ISSUE TITLE
Create a dataset loader for Hallmarks of Cancer

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#58]
From https://github.com/sb895/Hallmarks-of-Cancer

**Comment by mdmanurung** [comment]
#self-assign

**Comment by mdmanurung** [comment]
Hi @hakunanatasha, I noticed that there's already some work on this in the examples folder: https://github.com/bigscience-workshop/biomedical/blob/master/examples/hallmarks_of_cancer.py

So is this task redundant?
