### ISSUE TITLE
Potential Authorship Contributions

### ISSUE THREAD

**Issue by rosalinesway** [bigscience-workshop/biomedical#586]
Hi @GullyBurns and @tonifuc3m! Thanks for contributing to the hackathon! Currently, we will only _acknowledge_ participants who have implemented < 3 datasets. Would you be willing to implement 2 more datasets (of the 29 outstanding datasets) if you have the bandwidth? That will make sure you can meet the authorship threshold. The deadline to do so is to raise 2 more PRs by **next week**. 
Let me know if you are interested!

**Comment by davidkartchner** [comment]
@rosalinesway What is the deadline for implementing 3+ datasets to receive authorship?  I discovered this project today,  but will finish a PR for one dataset tomorrow and could implement two more by the end of Saturday.  Would I still be able to get authorship on the paper?

**Comment by GullyBurns** [comment]
Dear Rosaline, 

I only just saw this note. What is the current situation with respect to deadlines etc?

Thanks

Gully

**Comment by jason-fries** [comment]
Hi @GullyBurns ,
To receive authorship (see [contributions list](https://docs.google.com/spreadsheets/d/1_rMzNXiO9_DUy9hTYj1vpOvz7KcETGiQjuCBvn-KM0s/edit?usp=sharing)) we'd need you to implement 2+ dataloaders from our [project board](https://github.com/orgs/bigscience-workshop/projects/6/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status), with the following datasets being top priority. 

- https://github.com/bigscience-workshop/biomedical/issues/60
- https://github.com/bigscience-workshop/biomedical/issues/227
- https://github.com/bigscience-workshop/biomedical/issues/356
- https://github.com/bigscience-workshop/biomedical/issues/41

These would realistically need to be done by Monday to provide time for our data auditing and other OA/QC measures.

**Comment by GullyBurns** [comment]
I realise. I regret that I will not be able to contribute sufficiently to receive authorship in this situation (I have too many other commitments). I will try to continue to help clear the backlog going forward regardless.

G

**Comment by shamikbose** [comment]
@jason-fries @ruisi-su Are these still the highest priority datasets? I can try doing #60 or #356. The other ones require training and user credentials
