### ISSUE TITLE
CRITICAL - Authorship Information Required 

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#605]
Dear Hackathon Participants, 
To receive authorship credit on our forthcoming dataset manuscript, we need all contributors to complete the following
- Add your preferred name, contact information, and affiliation to our [Contributor Spreadsheet](https://docs.google.com/spreadsheets/d/1_rMzNXiO9_DUy9hTYj1vpOvz7KcETGiQjuCBvn-KM0s/edit?usp=sharing)
- Make certain you have an https://openreview.net/ account. **Do not do this last minute.** 

If you are mentioned below, **we do not have your information**. Please complete the above ASAP and no later than May 27, 2022. We cannot update authorship after the paper is submitted. 

- [x] @HallerPatrick 
- [x] @jdposada 
- [x] @JohnGiorgi 
- [x] @mapama247 
- [x] @mariosaenger 
- [x] @mart1nro 
- [ ] @mcullan 
- [x] @nadahlberg
- [ ] @napsternxg
- [x] @nbroad1881 
- [x] @qanastek
- [x] @s-desh 
- [x] @sidkiblawi 
- [x] @whoisjones

**Comment by sidkiblawi** [comment]
Do we just add our contact info in the “ACL Workshop” sheet or is there a
different place you’d rather have it?
