### ISSUE TITLE
Create a dataset loader for GENIA PTM event corpus

### ISSUE THREAD

**Issue by ruisi-su** [bigscience-workshop/biomedical#607]
## Adding a Dataset
- **Name:** GENIA PTM event corpus
- **Description:** *extraction of multiple PTM types at once in a unified framework.*
- **Task:** *NER*
- **Paper:** *[paper](https://aclanthology.org/W11-0215.pdf)*
- **Data:** *[data](http://www.geniaproject.org/other-corpora/ptm-event-corpus)*
- **License:** *CC BY 3.0*
- **Motivation:** *this dataset used in inBoXBART*

**Comment by albertvillanova** [comment]
#self-assign
