### ISSUE TITLE
Create a dataset loader for GAD corpus

### ISSUE THREAD

**Issue by ruisi-su** [bigscience-workshop/biomedical#608]
## Adding a Dataset
- **Name:** *Genetic Association Database Corpus*
- **Description:** *a corpus identifying associations between genes and diseases by a semi-automatic annotation procedure based on the Genetic Association Database*
- **Task:** *RE*
- **Paper:** *[paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4466840/)*
- **Data:** *[data](https://drive.google.com/file/d/1-jDKGcXREb2X9xTFnuiJ36PvsqoyHWcw/view)* from [this](https://github.com/dmis-lab/biobert/issues/153) issue
- **License:** *CC BY 4.0*
- **Motivation:** *part of BLURB*

**Comment by ruisi-su** [comment]
Thanks @tmabraham for looking into this. I remember about GAD's labels generating confusions when I was tracking down this dataset. This issue was created to stay consistent with the BLURB dataset. However, I think your point (along with others' concern about this dataset) is very valid. We will postpone this and put a lower priority for now.

**Comment by SamuelCahyawijaya** [comment]
#self-assign
