### ISSUE TITLE
Create a dataset load for Medical Drugs Sentiment Analysis Corpus

### ISSUE THREAD

**Issue by ruisi-su** [bigscience-workshop/biomedical#609]
## Adding a Dataset
- **Name:** *Medical Drugs*
- **Description:** *Medical Drugs Sentiment Analysis with Multi-classes*
- **Task:** *Text Classification*
- **Data:** *[data](https://www.kaggle.com/datasets/arbazkhan971/analyticvidhyadatasetsentiment)*
- **License:** *Unknown*
- **Motivation:** *part of InBoXBART training dataset*

**Comment by shamikbose** [comment]
@ruisi-su I can try and handle this dataloader. What should it be named? Also, I noticed it's marked High Priority. Is there a date you need this by?

**Comment by ruisi-su** [comment]
@shamikbose That will be great! Ideally we would want this by next week as well. It was named as just "medical drugs" in the paper. @jason-fries any preference on naming conventions on this dataset?

**Comment by shamikbose** [comment]
#self-assign

**Comment by jason-fries** [comment]
@ruisi-su @shamikbose 
Sheesh this dataset is a real mystery! Almost no information provided (where did it come from, who labeled it, licensing, etc.) For matching `InBoXBART` I guess we have to include it, so let's proceed with implementing and using the  "medical drugs" name per the paper.

**Comment by shamikbose** [comment]
@jason-fries  Thanks for the clarification!  Since it has none of the licensing information or a homepage, what should I set those variables to?

**Comment by shamikbose** [comment]
@jason-fries @ruisi-su This has been completed and is in PR #613
