### ISSUE TITLE
Create a dataset loader for SPL-ADR-200db - Adverse Drug Reactions

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#61]
From https://bionlp.nlm.nih.gov/tac2017adversereactions/

**Comment by MFreidank** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @MFreidank, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by MFreidank** [comment]
Hi @hakunanatasha, yes, I'm working on this :)
Will open a PR once I have a first draft implementation ready.

**Comment by hakunanatasha** [comment]
@MFreidank sounds wonderful! ping us anytime if you need help! Looking forward to your PR!
