### ISSUE TITLE
Create a dataset loader for CodiEsp

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#64]
From https://zenodo.org/record/3837305#.YL46cfdfjMU

**Comment by mapama247** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @mapama247, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by mapama247** [comment]
yes @hakunanatasha !

**Comment by hakunanatasha** [comment]
@mapama247 awesome, looking forward to that PR 🌸

**Comment by leondz** [comment]
I spent coincidentally built a loader for this last week - lmk if you're unable to complete :)

**Comment by jason-fries** [comment]
Hi @mapama247 
Just a ping on the status of this dataset. Please let us know if you are still working on it and when you plan to submit a PR. Otherwise if we don't hear back soon, @leondz you are welcome to submit your version. Thanks!!

**Comment by mapama247** [comment]
hi @jason-fries 
Actually I did a PR one week ago (https://github.com/bigscience-workshop/biomedical/pull/453) that got some review comments yesterday.  I have just started replying the reviewer but @leondz feel free to check if something looks odd to you.
