### ISSUE TITLE
bc2g[mn] vs gnormplus

### ISSUE THREAD

**Issue by galtay** [bigscience-workshop/biomedical#676]
What exactly are the differences between the gnormplus dataset and the biocreative II datasets (BC2GM & BC2GN)  

* https://biocreative.bioinformatics.udel.edu/resources/corpora/biocreative-ii-corpus/
* https://www.ncbi.nlm.nih.gov/research/bionlp/Tools/gnormplus/

currently only gnormplus is implemented 
https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/biodatasets/gnormplus/gnormplus.py

but BLURB uses BC2GM
https://microsoft.github.io/BLURB/tasks.html

this issue is to sort out the differences and potentially implement the BC2 tasks

**Comment by hakunanatasha** [comment]
We implemented BC2GM in BLURB; we may need to shift this into its own dataloader
