### ISSUE TITLE
Fix Datasets Currently Mapped as Tasks.TEXTUAL_ENTAILMENT

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#682]
Several datasets are currently tagged as supporting `Tasks.TEXTUAL_ENTAILMENT` incorrectly. Perhaps I'm misunderstanding the tasks, but these largely seem like text classification/labeling problems not entailment. 

- [medical_data](https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/biodatasets/medical_data/medical_data.py) is a sentiment analysis task not textual entailment. Better suited to pairs or text classification 
- [evidence_inference](https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/biodatasets/evidence_inference/evidence_inference.py) this is labeling a relationship between text snippets i.e., "intervention of interest either significantly increased, significantly decreased or had significant effect on the outcome, relative to the comparator"

Fix is migrating these to the correct schema

**Comment by shamikbose** [comment]
@jason-fries The issue with medical_data is addressed in  the conversation in #613
> So every text comes with a drug mention and what the text thinks of that specific drug. Putting this in the Classification format loses some of that information

**Comment by jason-fries** [comment]
@shamikbose thanks for the comment. If a simple classification schema isn’t suited then this should be a text pairs task if it involves reasoning over 2 units of text. The most important issue is that this is not an entailment task.

**Comment by shamikbose** [comment]
I can tackle the medical_data tomorrow

**Comment by shamikbose** [comment]
@jason-fries medical_data is updated to bigbio_pairs in #684

**Comment by phlobo** [comment]
Both datasets mentioned here now have other tasks assigned, therefore I will close the issue.
