### ISSUE TITLE
quaero: missing NED

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#702]
From the corpus webpage: https://quaerofrenchmed.limsi.fr/
```
 T1 PROC 3 16 contraception
#1 AnnotatorNotes T1 C0700589
T2 DEVI 25 50 dispositifs intra utérins
#2 AnnotatorNotes T2 C0021900
T3 ANAT 43 50 utérins
#3 AnnotatorNotes T3 C0042149 
```
The `AnnotatorNotes` are UMLS codes

**Comment by phlobo** [comment]
I would be happy to contribute to this issue. 

However, I noticed that the MEDLINE test split contains only 832 documents (vs. 833 according to the [paper](http://ceur-ws.org/Vol-1609/16090028.pdf)) and the number of entities in this split is also slightly lower than reported in the paper. 

The BRAT version of Quaero seems to have all the 833 documents.

Would it be preferable to change the dataset loader to use the BRAT version?

**Comment by leonweber** [comment]
Ideally we would have both as different configs and make the more complete (BRAT) the default one

**Comment by phlobo** [comment]
I assume that the BioC version was generated from the BRAT files. Because one of the BRAT annotations for one of the documents has no CUI, the complete document was (erroneously) omitted. 

I will submit a PR once #731 is clarified.
