### ISSUE TITLE
Create a dataset loader for CANTEMIST (CANcer TExt Mining Shared Task)

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#72]
From https://temu.bsc.es/cantemist/

**Comment by hakunanatasha** [comment]
Hi @mapama247, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins)

**Comment by mapama247** [comment]
Hi @hakunanatasha! Yes, I have not finished yet but I plan to do it before the deadline ends.
