### ISSUE TITLE
Check for libraries like modin

### ISSUE THREAD

**Issue by shamikbose** [bigscience-workshop/biomedical#728]
A number of these datasets (eg. `medal`) involves reading large CSV files. This can be considerably sped up if the dataset loader checks for the presence of a library like modin which is a drop-in replacement for pandas for most tasks.

Something like
```
if 'modin' in sys.modules():
  import modin.pandas as pd
else:
  import pandas as pd
```

**Comment by shamikbose** [comment]
I tried to build a version of this, but I get this error
`ImportError: To be able to use medal, you need to install the following dependencies['sys,'] using 'pip install sys,' for instance'`
Have there been any recen changes to cause this?

**Comment by hakunanatasha** [comment]
This is a good idea but will require a bit more exploration - please join our discord and ping about this there!
