### ISSUE TITLE
Create a dataset loader for Swedish Medical NER

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#73]
From https://github.com/olofmogren/biomedical-ner-data-swedish

**Comment by bwang482** [comment]
https://huggingface.co/datasets/swedish_medical_ner

**Comment by bwang482** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi Bo! How's it going : ) let us know if you have questions!

**Comment by jason-fries** [comment]
This is being worked on for PR https://github.com/bigscience-workshop/biomedical/pull/462
