### ISSUE TITLE
Multiple normalizations per entity

### ISSUE THREAD

**Issue by phlobo** [bigscience-workshop/biomedical#731]
Dear all,

I am trying to add NED annotations for different datasets (e.g., [Quaero](https://github.com/bigscience-workshop/biomedical/issues/702) and [DisTEMIST](https://github.com/bigscience-workshop/biomedical/issues/695)), and I wonder how to use the `normalized` attribute when there are multiple concept annotations for an entity in the source.

Case 1) 
For DisTEMIST, a single complex entity can contain multiple concepts, e.g.:
"adenopatías laterocervicales ipsilaterales tanto submaxilares como yugulodigástricas" is annotated with two SNOMED CT codes (127087005+127082004).

Case 2)
For many datasets like Quaero (but also MantraGSC or MedMentions), it is possible that entities have multiple normalizations, usually meaning that the mapping is ambiguous.

In my opinion, for case 1, these are actually two entities which share the same span, while for case 2 it's the same entity, so (as a user of the library) I would prefer to have a list of possible normalizations for that same entity in case 2.

This, however, is not how it is currently implemented for Mantra (https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/biodatasets/mantra_gsc/mantra_gsc.py) or MedMentions (https://github.com/bigscience-workshop/biomedical/blob/master/bigbio/biodatasets/medmentions/medmentions.py) where each annotation becomes a new entity.

Example from Mantra:
``` 
{'id': '0084_d144.u226_T18', 'type': 'DISO', 'text': ['esterilidad'], 'offsets': [[66, 77]], 'normalized': [{'db_name': 'UMLS', 'db_id': 'C0678108'}]}
{'id': '0084_d144.u226_T21', 'type': 'DISO', 'text': ['esterilidad'], 'offsets': [[66, 77]], 'normalized': [{'db_name': 'UMLS', 'db_id': 'C0021359'}]}
```

What is the intended use of passing a list to `normalized`?

**Comment by galtay** [comment]
Thanks for creating this issue and the examples @phlobo . My initial reaction is leaning towards using a single entity with multiple normalizations in all cases. @jason-fries @leonweber @shamikbose @sg-wbi what do you think here?

**Comment by shamikbose** [comment]
@galtay I agree. Single entity with multiple normalizations would cover a lot of cases. How would they be uniquely identified, though? Offsets?

**Comment by jason-fries** [comment]
@galtay @phlobo @shamikbose We've chatted at various points at a schema change that would address these issues. I think modifying the KB schema to something like 
```
"entities": [
    {
        "id": datasets.Value("string"),
        "text": datasets.Sequence(datasets.Value("string")),
        "offsets": datasets.Sequence([datasets.Value("int32")]),  
        "type": [
            "name": datasets.Value("string"),
            "normalized": [
                {
                    "db_name": datasets.Value("string"),
                    "db_id": datasets.Value("string"),
                }
            ],
        ],      
    }
],
```
would handle our current representation limitations 
- Supports spans with multiple types (e.g., MedMentions
- Keeps spans unique
- Normalizations link to a specific types (or if only NED info is provided, the type here would be the database name) 

Thoughts?

**Comment by galtay** [comment]
@phlobo to add a little more context, we didn't have a hard rule for "what does a list of normalizations mean", we just had datasets that had 0 or more normalizations per entity and wanted to represent that. 

For Case 1 above, I don't think there is an obvious "best" way to represent that and I think putting both codes in a normalization list is no worse than any other solution. 

For Case 2 I think it's also fine to put the normalizations into a single list. 

So, until we update the schema, I think we should create issues to update the existing datasets like mantra and medmentions that have multiple copies of entities and feel fine about adding new datasets with the existing schema using lists of normalizations.

**Comment by phlobo** [comment]
@galtay Thanks for the clarification!

If I understand @jason-fries correctly, the current schema does not support representing entities with different types:

Example from Quaero:
```
{'id': '318_T462', 'type': 'DISO', 'text': ['voies urinaires'], 'offsets': [[11693, 11708]], 'normalized': [{'db_name': 'UMLS', 'db_id': 'C0042075'}]}
{'id': '318_T463', 'type': 'ANAT', 'text': ['voies urinaires'], 'offsets': [[11693, 11708]], 'normalized': [{'db_name': 'UMLS', 'db_id': 'C0042027'}]}
```

I assume these should remain separate entities for now?

**Comment by jason-fries** [comment]
Hi @phlobo, 
That's correct -- for now you'll have to represent every type as a unique (but duplicated) entity span.

**Comment by Parlagprs** [comment]
Hiii

**Comment by Parlagprs** [comment]
Okkkkkkkk

**Comment by hakunanatasha** [comment]
handled in #733

**Comment by phlobo** [comment]
@hakunanatasha I'm afraid this issue is not resolved yet - the current ambiguity regarding multiple normalizations per entity (for the different reasons they might occur) could be handled with an updated schema
