### ISSUE TITLE
Create a dataset loader for QUAERO

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#74]
From https://quaerofrenchmed.limsi.fr

**Comment by giganttheo** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @giganttheo  - keep us posted on the status via discord or ideally a ping here!

**Comment by giganttheo** [comment]
Hi @hakunanatasha . I am still working on it, it's almost finished, I am sending a merge request in a few days for this dataset script :)

**Comment by hakunanatasha** [comment]
@giganttheo awesome, im really looking forward to your PR 🌸

**Comment by qanastek** [comment]
## Adding a Dataset
- **Name:** *Quaero French Medical Corpus*
- **Description:** *In this paper, we report on the development of an extensive corpus of biomedical documents in French annotated at the entity and concept level. Three text genres are covered, comprising a total of 103,056 words. Ten entity categories corresponding to UMLS Semantic Groups were annotated, using automatic pre-annotations validated by trained human annotators. The pre-annotation method was found helful for entities and achieved above 0.83 precision for all text genres. Overall, a total of 26,409 entity annotations were mapped to 5,797 unique UMLS concepts.*
- **Task:** *NER ; Entity Normalization*
- **Paper:** *http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.672.946*
- **Data:** *https://quaerofrenchmed.limsi.fr/*
- **License:** *GNU Common Public License v.3.0*
- **Motivation:** *This is the biggest NER corpus for biomedical in French.*
