### ISSUE TITLE
Create a dataset loader for NLM-Chem

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#80]
- Task: NER, NEN, Document Indexing
- License: "This work is licensed under a CC0 1.0 Universal (CC0 1.0) Public Domain Dedication license."
- Format: BioC
- Language: English
- Citation:
@article{islamaj2021nlm,
  title={NLM-Chem, a new resource for chemical entity recognition in PubMed full text literature},
  author={Islamaj, Rezarta and Leaman, Robert and Kim, Sun and Kwon, Dongseop and Wei, Chih-Hsuan and Comeau, Donald C and Peng, Yifan and Cissel, David and Coss, Cathleen and Fisher, Carol and others},
  journal={Scientific Data},
  volume={8},
  number={1},
  pages={1--12},
  year={2021},
  publisher={Nature Publishing Group}
}
- Suorce: https://datadryad.org/stash/dataset/doi:10.5061/dryad.3tx95x6dz

**Comment by hakunanatasha** [comment]
merged example closed
