### ISSUE TITLE
Add implementation of BioID

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#861]
## Adding a Dataset
- **Name:** *BioID*
- **Description:** *Multi-type NER and NED in PubMed figure captions*
- **Task:** *NER, NED*
- **Paper:** *[link to the dataset paper](https://biocreative.bioinformatics.udel.edu/media/store/files/2018/BC6_track1_1.pdf)*
- **Data:** *[link to the Github repository or current dataset location](https://biocreative.bioinformatics.udel.edu/tasks/biocreative-vi/track-1/)*
- **License:** *Unknown*
- **Motivation:** *Cell lines normalized to Cellosaurus*

**Comment by davidkartchner** [comment]
@sg-wbi Thanks so much for adding this!
