### ISSUE TITLE
Wrong parsing of some documents with CARDIO:DE loader

### ISSUE THREAD

**Issue by nachollorca** [bigscience-workshop/biomedical#888]
## Describe the bug
Some documents from CARDIO:DE dataset miss some passages with the [current loader](https://github.com/bigscience-workshop/biomedical/blob/main/bigbio/hub/hub_repos/cardiode/cardiode.py) due to a bug in the reading of the WebAnno TSV3 files.

## Steps to reproduce the bug
```python
from datasets import load_dataset
load_dataset("bigbio/cardiode", data_dir='...')
```

## Expected results
All passages and entities are loaded with the correct offsets mapped.

## Actual results
Documents with character '#' spread through the body of the .TSV files get incorrect offsets.

## Environment info
- `datasets` version: 2.9.0
- Platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyArrow version: 11.0.0
- Pandas version: 1.5.3

**Comment by galtay** [comment]
fixed by #890
