### ISSUE TITLE
Create a dataset loader for NLM-Gene

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#91]
- Task: NER, NEN
- License: "This work is licensed under a CC0 1.0 Universal (CC0 1.0) Public Domain Dedication license."
- Format: BioC
- Language: English
- Citation:
@article{islamaj2021nlm,
  title={NLM-Gene, a richly annotated gold standard dataset for gene entities that addresses ambiguity and multi-species gene recognition},
  author={Islamaj, Rezarta and Wei, Chih-Hsuan and Cissel, David and Miliaras, Nicholas and Printseva, Olga and Rodionov, Oleg and Sekiya, Keiko and Ward, Janice and Lu, Zhiyong},
  journal={Journal of Biomedical Informatics},
  volume={118},
  pages={103779},
  year={2021},
  publisher={Elsevier}
}
- Suorce: https://zenodo.org/record/5089049

**Comment by vumichien** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @vumichien, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins). I see that you're active on the discord so we are greatly looking forward to your submission!

**Comment by vumichien** [comment]
Hi @hakunanatasha  I am still working on it
