### ISSUE TITLE
Create a dataset loader for LINNAEUS

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#92]
- Task: NER, NEN
- License: "Creative Commons Attribution 4.0 International (CC BY 4.0)"
- Format: text files + annotation file
- Language: English
- Citation:
@article{gerner2010linnaeus,
  title={LINNAEUS: a species name identification system for biomedical literature},
  author={Gerner, Martin and Nenadic, Goran and Bergman, Casey M},
  journal={BMC bioinformatics},
  volume={11},
  number={1},
  pages={1--17},
  year={2010},
  publisher={BioMed Central}
}
- Source: http://linnaeus.sourceforge.net/

**Comment by sg-wbi** [comment]
https://huggingface.co/datasets/linnaeus

**Comment by whoisjones** [comment]
#self-assign
