### ISSUE TITLE
Unittests tests.test_bigbio_hub bioasq_task_b are failing

### ISSUE THREAD

**Issue by mart1nro** [bigscience-workshop/biomedical#924]
## Describe the bug

"runTest (__main__.TestDataLoader) [Check multiple choice]" is failing. This is because  "choices" is always set to [] for each record in _generate_examples, even for yesno questions:
https://github.com/bigscience-workshop/biomedical/blob/5c9e606097844db49ca2f7151e2a349f67c0d2cd/bigbio/hub/hub_repos/bioasq_task_b/bioasq_task_b.py#L791

Tests for bioasq10b are failing with datasets.exceptions.DatasetGenerationError because there is no "BioASQ-training10b" folder in "BioASQ-training10b.zip" and the path "BioASQ-training10b/training10b.json" is incorrect:
https://github.com/bigscience-workshop/biomedical/blob/5c9e606097844db49ca2f7151e2a349f67c0d2cd/bigbio/hub/hub_repos/bioasq_task_b/bioasq_task_b.py#L698

The correct path should be "training10b.json", similar to the bioasq_8b example.

## Steps to reproduce the bug

Download dataset zips of task b from http://participants-area.bioasq.org/datasets/ and put them into a data_dir

```shell
python -m tests.test_bigbio_hub bioasq_task_b --data_dir /home/robert/Desktop/bioasq --test_local
```

## Expected results
All tests pass.

## Actual results
See attached test_output.txt
[test_output.txt](https://github.com/user-attachments/files/16029554/test_output.txt)

## Environment info

- `datasets` version: 2.20.0
- Platform: Linux-6.9.5-arch1-1-x86_64-with-glibc2.34
- Python version: 3.8.19
- `huggingface_hub` version: 0.23.4
- PyArrow version: 16.1.0
- Pandas version: 2.0.3
- `fsspec` version: 2024.5.0

**Comment by phlobo** [comment]
closed by #926
