### ISSUE TITLE
Create a dataset loader for tmVar

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#93]
- Task: NER, NEN
- License: ? "freely available"
- Format: PubTator
- Language: English
- Citation:
@article{wei2018tmvar,
  title={tmVar 2.0: integrating genomic variant information from literature with dbSNP and ClinVar for precision medicine},
  author={Wei, Chih-Hsuan and Phan, Lon and Feltz, Juliana and Maiti, Rama and Hefferon, Tim and Lu, Zhiyong},
  journal={Bioinformatics},
  volume={34},
  number={1},
  pages={80--87},
  year={2018},
  publisher={Oxford University Press}
}
- Source: 
* all: https://www.ncbi.nlm.nih.gov/research/bionlp/Tools/tmvar/
* v1 (NER): https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/tmVar/tmVarCorpus.zip
* v2 (NER+NEN): https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/tmVar/tmVar.Normalization.txt

**Comment by galtay** [comment]
Hi I would like to work on this dataset (if sg-wbi doesn't want it)

**Comment by sg-wbi** [comment]
Sure go ahead!

**Comment by jason-fries** [comment]
Hey @galtay, do you still want to work on this or free it up for participants :)

**Comment by galtay** [comment]
Yes, sorry! I'm interested in variant datasets in general, but have spent more time reviewing PRs than writing dataset loaders. I'm happy to free this up and then if no one takes it during the hackathon I can take a look.

**Comment by shamikbose** [comment]
#self-assign

**Comment by shamikbose** [comment]
@galtay @jason-fries I'd like to work on this dataset if nobody else is assigned to it
