### ISSUE TITLE
Add S800

### ISSUE THREAD

**Issue by mariosaenger** [bigscience-workshop/biomedical#934]
## Adding a Dataset
- **Name:** S800
- **Description:** a novel abstract-based manually annotated corpus. S800 comprises 800 PubMed abstracts in which organism mentions were identified and mapped to the corresponding NCBI Taxonomy identifiers.
- **Task:** NER
- **Paper:** [https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0065390&type=printable](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0065390&type=printable)
- **Data:**[https://species.jensenlab.org/](https://species.jensenlab.org/)
- **License:** *Type of license; please provide public for new datasets*

https://github.com/spyysalo/s800
https://spyysalo.github.io/s800-revision-docs/

**Comment by phlobo** [comment]
Duplicate of #27 ?

**Comment by mariosaenger** [comment]
Yes. I'll close it
