### ISSUE TITLE
Add CRAFT

### ISSUE THREAD

**Issue by mariosaenger** [bigscience-workshop/biomedical#938]
## Adding a Dataset
- **Name:** CRAFT
- **Description:** This repository contains the CRAFT corpus, a collection of 97 articles from the PubMed Central Open Access subset, each of which has been annotated along a number of different axes spanning structural, coreference, and concept annotation.
- **Task:** NER,NEN
- **Paper:** https://inria.hal.science/hal-01159065/document
- **Data:** https://github.com/UCDenver-ccp/CRAFT
- **License:** Creative Commons BY 3.0 license.

**Comment by phlobo** [comment]
closed by #681
