### ISSUE TITLE
Create a dataset loader for Thomas et al. (2011)

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#94]
- Task: NER, NEN
- License: ?
- Format: annotation file
- Language: English
- Citation:
@Article{thomas2011,
	author = {Thomas, Philippe and Klinger, Roman and Furlong, Laura and Hofmann-Apitius, Martin and Friedrich, Christoph}, 
	title = {Challenges in the association of human single nucleotide polymorphism mentions with unique database identifiers}, 
	journal = {BMC Bioinformatics}, 
	volume = {12}, 
	year = {2011}, 
	number = {Suppl 4}, 
	pages = {S4}, 
	url = {http://www.biomedcentral.com/1471-2105/11/S4/S4}, 
	doi = {10.1186/1471-2105-12-S4-S4}, 
	issn = {1471-2105} 
}
- Source: https://github.com/rockt/SETH/tree/master/resources/thomas2011

**Comment by GullyBurns** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @GullyBurns looking forward to your submission : ) let us know if you need any assistance by pinging the admins (@jason-fries @leonweber @galtay @debajyotidatta @sunnnymskang @sg-wbi)

**Comment by jason-fries** [comment]
Hi @GullyBurns 
Just a ping on this dataset :) Let us know if we can help with any implementation details. Thanks!

**Comment by GullyBurns** [comment]
I'm sorry for the delay. I'm working on it now.

G

**Comment by GullyBurns** [comment]
Hi Admins! (@jason-fries @leonweber @galtay @debajyotidatta @sunnnymskang @sg-wbi)

I've implemented a solution for this dataset but the dataset as is does not contain the text for annotations, just the annotations themselves. Consequently, the mapped schema contains entities but no passages. 

In its current form, the test scripts pass complains in the following way for all entries:

> Example:15098000 - entity:7  text:`Val158Met` != text_by_offset:``

I could attempt to download the referenced pubmed text from NCBI's eutils services in the script but that would require some additional dependencies in the library and I'm not sure how the licensing would work for that process. 

As it is the code is ready to be merged, but I wanted to check with you all before I sent it as a PR.

Any feedback on this would be welcome.

Gully

**Comment by sg-wbi** [comment]
Hey @GullyBurns thank you for your contribution! Could you please open a "Pull request" with your script? This way we can have a look at your implementation.

> but the dataset as is does not contain the text for annotations, just the annotations themselves.

This is something that can happen unfortunately. We are still discussing how to handle datasets that are de facto incomplete and we should also be able to soon to bypass some of the tests as a  workaround. As of now we will knowingly allow some of the tests to fail and label the dataset as "incomplete".
