### ISSUE TITLE
Create a dataset loader for SETH-corpus

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#96]
- Task: NER
- License: Apache License, Version 2.0
- Format: brat
- Language: English
- Citation:
@Article{SETH2016,
  Title= {SETH detects and normalizes genetic variants in text.},
  Author= {Thomas, Philippe and Rockt{\"{a}}schel, Tim and Hakenberg, J{\"{o}}rg and Lichtblau, Yvonne and Leser, Ulf},
  Journal= {Bioinformatics},
  Year= {2016},
  Month= {Jun},
  Doi= {10.1093/bioinformatics/btw234},  
  Language = {eng},
  Medline-pst = {aheadofprint},
  Pmid = {27256315},
  Url = {http://dx.doi.org/10.1093/bioinformatics/btw234}
}
- Source: https://github.com/rockt/SETH/tree/master/resources/SETH-corpus

**Comment by vumichien** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
Hi @vumichien, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either ping me here at @hakunanatasha  or ping the discord admins (with @admins). I see you on the Discord so ping us there if it's easier than a comment here : )

**Comment by vumichien** [comment]
@hakunanatasha I have made a PR in here #346
