### ISSUE TITLE
Create a dataset loader for Verspoor2013

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#97]
- Task: NER, RE
- License: ?
- Format: brat
- Language: English
- Citation:
@article{verspoor2013annotating,
  title={Annotating the biomedical literature for the human variome},
  author={Verspoor, Karin and Jimeno Yepes, Antonio and Cavedon, Lawrence and McIntosh, Tara and Herten-Crabb, Asha and Thomas, Zo{\"e} and Plazzer, John-Paul},
  journal={Database},
  volume={2013},
  year={2013},
  publisher={Oxford Academic}
}
- Source: https://github.com/rockt/SETH/tree/master/resources/Verspoor2013

**Comment by mcullan** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
@mcullan were you assigned to this? seems like it somehow dropped you!

**Comment by hakunanatasha** [comment]
please ping me at @hakunanatasha in case it doesnt work and ill manually assign you

**Comment by mcullan** [comment]
@hakunanatasha thanks - I noticed the assignment bot didn't work. Yes, please assign me!

**Comment by hakunanatasha** [comment]
@mcullan done! I suppose it was taking a little break :P
