### ISSUE TITLE
Create a dataset loader for AskAPatient

### ISSUE THREAD

**Issue by sg-wbi** [bigscience-workshop/biomedical#99]
- Task: NER, NEN
- License: Creative Commons Attribution 4.0 International
- Format: BioC
- Language: English
- Citation:
@inproceedings{limsopatham2016normalising,
  title={Normalising medical concepts in social media texts by learning semantic representation},
  author={Limsopatham, Nut and Collier, Nigel},
  booktitle={Proceedings of the 54th annual meeting of the association for computational linguistics (volume 1: long papers)},
  pages={1014--1023},
  year={2016}
}
- Source: https://zenodo.org/record/55013#.YgpAHVvMJhE

**Comment by j-chim** [comment]
#self-assign
